#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.Web.Views.CurrentUser
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CurrentUser/LoggedOnName.cshtml")]
    public partial class LoggedOnName : System.Web.Mvc.WebViewPage<BudgetOnline.Web.ViewModels.CurrentUserViewModel>
    {
        public LoggedOnName()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
  
	Layout = null;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 6 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
 if(Model.IsLoggedOn)  {

            
            #line default
            #line hidden
WriteLiteral("\t<div>Пользователь: <a href=\"");


            
            #line 7 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
                        Write(Url.Action("index", "profile"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 7 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
                                                         Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n");



WriteLiteral("\t<div>\r\n\t\t<a href=\"");


            
            #line 9 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
      Write(Url.Action("index", "logout"));

            
            #line default
            #line hidden
WriteLiteral("\">Log out</a>\r\n\t</div>\r\n");


            
            #line 11 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("\t<div>\r\n\t\t<a href=\"");


            
            #line 13 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
      Write(Url.Action("index", "login"));

            
            #line default
            #line hidden
WriteLiteral("\">Login</a>\r\n\t</div>\r\n");


            
            #line 15 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
