#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CurrentUser/LoggedOnName.cshtml")]
    public partial class _Views_CurrentUser_LoggedOnName_cshtml : System.Web.Mvc.WebViewPage<BudgetOnline.Web.ViewModels.CurrentUserViewModel>
    {
        public _Views_CurrentUser_LoggedOnName_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
  
	Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
 if(Model.IsLoggedOn)  {

            
            #line default
            #line hidden
WriteLiteral("\t<div>Пользователь: <a");

WriteAttribute("href", Tuple.Create(" href=\"", 131), Tuple.Create("\"", 169)
            
            #line 7 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
, Tuple.Create(Tuple.Create("", 138), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "profile")
            
            #line default
            #line hidden
, 138), false)
);

WriteLiteral(">");

            
            #line 7 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
                                                         Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n");

WriteLiteral("\t<div>\r\n\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 207), Tuple.Create("\"", 244)
            
            #line 9 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
, Tuple.Create(Tuple.Create("", 214), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "logout")
            
            #line default
            #line hidden
, 214), false)
);

WriteLiteral(">Log out</a>\r\n\t</div>\r\n");

            
            #line 11 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("\t<div>\r\n\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 290), Tuple.Create("\"", 326)
            
            #line 13 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
, Tuple.Create(Tuple.Create("", 297), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "login")
            
            #line default
            #line hidden
, 297), false)
);

WriteLiteral(">Login</a>\r\n\t</div>\r\n");

            
            #line 15 "..\..\Views\CurrentUser\LoggedOnName.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
