#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/_AnonimousPage.cshtml")]
    public partial class _Views__AnonimousPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views__AnonimousPage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral("></meta>\r\n    <title>Бюджет On-Line :: ");

            
            #line 5 "..\..\Views\_AnonimousPage.cshtml"
                        Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 140), Tuple.Create("\"", 181)
            
            #line 6 "..\..\Views\_AnonimousPage.cshtml"
, Tuple.Create(Tuple.Create("", 147), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/site.css")
            
            #line default
            #line hidden
, 147), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 229), Tuple.Create("\"", 279)
            
            #line 7 "..\..\Views\_AnonimousPage.cshtml"
, Tuple.Create(Tuple.Create("", 236), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/bootstrap.min.css")
            
            #line default
            #line hidden
, 236), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        body\r\n        {\r\n            padding-top: 40px;\r\n            padding-b" +
"ottom: 40px;\r\n            background-color: #f5f5f5;\r\n        }\r\n    </style>\r\n<" +
"/head>\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\_AnonimousPage.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 664), Tuple.Create("\"", 715)
            
            #line 20 "..\..\Views\_AnonimousPage.cshtml"
, Tuple.Create(Tuple.Create("", 670), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery-2.1.0.min.js")
            
            #line default
            #line hidden
, 670), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 762), Tuple.Create("\"", 812)
            
            #line 21 "..\..\Views\_AnonimousPage.cshtml"
, Tuple.Create(Tuple.Create("", 768), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/modernizr-2.7.2.js")
            
            #line default
            #line hidden
, 768), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 859), Tuple.Create("\"", 907)
            
            #line 22 "..\..\Views\_AnonimousPage.cshtml"
, Tuple.Create(Tuple.Create("", 865), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootstrap.min.js")
            
            #line default
            #line hidden
, 865), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
