using System.CodeDom.Compiler;
using System.Web.Mvc;
using System.Web.WebPages;
using BudgetOnline.Web.ViewModels;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    [GeneratedCode("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Dashboard/Index.cshtml")]
    public partial class _Views_Dashboard_Index_cshtml : WebViewPage<DashboardViewModel>
    {
        public _Views_Dashboard_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Dashboard\Index.cshtml"
  
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Dashboard</h2>\r\n");

        }
    }
}
#pragma warning restore 1591
