#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.Web.Views.LogIn
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/LogIn/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<BudgetOnline.Web.ViewModels.Security.LogInViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\LogIn\Index.cshtml"
  
	ViewBag.Title = "Log In";
	Layout = "~/Views/_AnonimousPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

WriteLiteral("\t");

            
            #line 7 "..\..\Views\LogIn\Index.cshtml"
Write(Html.BudgetOnlineWeb().Form()
       	.Css("form-signin")
       	.Header("Введите логин")
       	.HeaderCss("form-signin-heading")
       	.Content(
			item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 13 "..\..\Views\LogIn\Index.cshtml"
			 	
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\LogIn\Index.cshtml"
      Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 14 "..\..\Views\LogIn\Index.cshtml"
			 	
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\LogIn\Index.cshtml"
      Html.EditorForModel());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n\t\t\t ");

WriteLiteralTo(__razor_template_writer, "\r\n");

            
            #line 16 "..\..\Views\LogIn\Index.cshtml"
})       	)
        .ActionsContent(
            item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 19 "..\..\Views\LogIn\Index.cshtml"
			 	
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\LogIn\Index.cshtml"
      Html.BudgetOnlineWeb().PrimaryButton().Caption("Войти").Build());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n\t\t\t ");

            
            #line 20 "..\..\Views\LogIn\Index.cshtml"
         }))
        .Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
