using System.CodeDom.Compiler;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;
using BudgetOnline.Web.UI.Controls;
using BudgetOnline.Web.ViewModels;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    #line 1 "..\..\Views\Profile\Index.cshtml"

#line default
    #line hidden
    
    [GeneratedCode("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Profile/Index.cshtml")]
    public partial class _Views_Profile_Index_cshtml : WebViewPage<ProfileViewModel>
    {
        public _Views_Profile_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Profile\Index.cshtml"
  
	var route = ViewContext.RequestContext.RouteData;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Profile\Index.cshtml"
  
	ViewBag.Title = "Profile";
	Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Profile\Index.cshtml"
Write(Html.BudgetOnlineWeb().Form(BudgetOnlineWebControls.FormTypes.Horizontal)
	.ActionUrl(Url.Action(route.GetRequiredString("action"), route.GetRequiredString("controller")))
	.Content(
		item => new HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

            
            #line 14 "..\..\Views\Profile\Index.cshtml"
WriteTo(__razor_template_writer, Html.EditorForModel());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

            
            #line 15 "..\..\Views\Profile\Index.cshtml"
     }))
	.Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
