using System.CodeDom.Compiler;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    #line 1 "..\..\Views\Shared\_Layout.cshtml"
#line default
    #line hidden

    [GeneratedCode("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_Layout.cshtml"
  
    Layout = "_LayoutMain.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-9 central-column\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 7 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-3 right-column\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
            Write(Html.BudgetOnlineWeb().Panel()
           .Header("Текущий баланс")
           .Content(Html.Action("CurrentBalanceByCurrencies", "TransactionStatistics"))
           .ContentRefreshUrl(Url.Action("CurrentBalanceByCurrencies", "TransactionStatistics")).Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
            Write(Html.BudgetOnlineWeb().Panel()
           .Header("Текущий баланс по счетам")
           .Content(Html.Action("LightTotalByAccounts", "TransactionStatistics"))
           .ContentRefreshUrl(Url.Action("LightTotalByAccounts", "TransactionStatistics")).Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 28 "..\..\Views\Shared\_Layout.cshtml"
           Write(RenderSection("RightBar", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

DefineSection("Header", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Header", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
