#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_LayoutMain.cshtml"
    using StackExchange.Profiling;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LayoutMain.cshtml")]
    public partial class LayoutMain : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LayoutMain()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>Бюджет On-Line :: ");


            
            #line 6 "..\..\Views\Shared\_LayoutMain.cshtml"
                        Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta charset=\"utf-8\" lang=\"en\" name=\"viewport\" content=\"width=devi" +
"ce-width, initial-scale=1.0\" />\r\n    <link href=\"");


            
            #line 8 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(Url.Content("~/Content/bootstrap.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"");


            
            #line 9 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(Url.Content("~/Content/bootstrap-responsive.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"");


            
            #line 10 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(Url.Content("~/Content/site.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"");


            
            #line 11 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(Url.Content("~/Content/cus-icons.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"");


            
            #line 12 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(Url.Content("~/Content/themes/flick/jquery-ui.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"");


            
            #line 13 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(Url.Content("~/Content/themes/flick/jquery.ui.theme.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"");


            
            #line 14 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(Url.Content("~/Content/bootstrap-select.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <script src=\"");


            
            #line 15 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/jquery-2.0.3.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 16 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/jquery.cookie.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 17 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/underscore.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 18 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/backbone.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    \r\n</head>\r\n<body>\r\n    \r\n    ");


            
            #line 23 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(Html.BudgetOnlineWeb().ProgressIndicator().BackgroundUrl(@Url.Content("~/Content/images/back1.jpg")).IndicatorUrl(@Url.Content("~/Content/images/ajax-loader.gif")).Class("progress-indicator").Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div class=\"container\" id=\"container\">\r\n        <div class=\"row-fluid\">\r\n" +
"            <div class=\"span8\">\r\n                <!--\r\n\t\t\t\t\t<h4 class=\"muted\">\r\n" +
"\t\t\t\t\t\tBudget online</h4> //-->\r\n            </div>\r\n            <div class=\"span" +
"2\">\r\n");


            
            #line 33 "..\..\Views\Shared\_LayoutMain.cshtml"
                   Html.RenderPartial("_LanguageSwitch"); 

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div class=\"span2\" style=\"text-align: right;\">\r\n");


            
            #line 36 "..\..\Views\Shared\_LayoutMain.cshtml"
                   Html.RenderAction("LoggedOnName", "CurrentUser", new { Area = "" }); 

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n        <div class=\"row-fluid\">\r\n");


            
            #line 40 "..\..\Views\Shared\_LayoutMain.cshtml"
              Html.RenderPartial("~/Views/Shared/TopNavligationMenu.cshtml");

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div class=\"row-fluid\">\r\n            <div class=\"span12\">" +
"\r\n                ");


            
            #line 44 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div class=\"row-fluid footer\">\r\n   " +
"         <div class=\"span12 muted\">\r\n                <p class=\"text-center\">\r\n  " +
"                  &copy; Company ");


            
            #line 50 "..\..\Views\Shared\_LayoutMain.cshtml"
                              Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <script src=\"");


            
            #line 54 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/jquery-ui-1.10.3.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 55 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/modernizr-2.6.2.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 56 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/bootstrap.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    ");



WriteLiteral("\r\n    <script src=\"");


            
            #line 58 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/jquery.validate.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    ");



WriteLiteral("\r\n    ");



WriteLiteral("\r\n    ");



WriteLiteral("\r\n    ");



WriteLiteral("\r\n    ");



WriteLiteral("\r\n    <script src=\"");


            
            #line 66 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/jsrender.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 67 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/bootstrap-select.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 68 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/common.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 69 "..\..\Views\Shared\_LayoutMain.cshtml"
            Write(Url.Content("~/Scripts/jquery.postdatas-min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    \r\n    ");


            
            #line 71 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(MiniProfiler.RenderIncludes(showTrivial: true, showTimeWithChildren: true, position: RenderPosition.Left));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n    ");


            
            #line 73 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(RenderSection("Header", false));

            
            #line default
            #line hidden
WriteLiteral(@"

    <script type=""text/javascript""><!--
        $(function () {
            $('#language-switch ul.dropdown-menu li a').click(function(e) {
                e.preventDefault();
                var lang = $(this).attr('data-lang');
                changeLang(lang);
            });
        });
	//-->
    </script>
</body>
</html>
");


        }
    }
}
#pragma warning restore 1591
