#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    
    #line 1 "..\..\Views\Shared\_LayoutMain.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\_LayoutMain.cshtml"
    using StackExchange.Profiling;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LayoutMain.cshtml")]
    public partial class _Views_Shared__LayoutMain_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__LayoutMain_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>  ");

WriteLiteral(@"
<head>
    <style>
        /* This helps the ng-show/ng-hide animations start at the right place. */
        /* Since Angular has this but needs to load, this gives us the class early. */
        .ng-hide {
            display: none!important;
        }
    </style>
    <title>Бюджет On-Line :: ");

            
            #line 14 "..\..\Views\Shared\_LayoutMain.cshtml"
                        Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/ico\"");

WriteLiteral(" href=\"/Content/images/favicon.ico\"");

WriteLiteral("/>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge, chrome=1\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, " +
"user-scalable=no\"");

WriteLiteral(" />\r\n    \r\n    <!-- Turn off caching -->\r\n    <meta");

WriteLiteral(" http-equiv=\"cache-control\"");

WriteLiteral(" content=\"max-age=0\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"cache-control\"");

WriteLiteral(" content=\"no-cache\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"expires\"");

WriteLiteral(" content=\"0\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"expires\"");

WriteLiteral(" content=\"Tue, 01 Jan 1980 1:00:00 GMT\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"pragma\"");

WriteLiteral(" content=\"no-cache\"");

WriteLiteral(" />\r\n    \r\n    <!-- Turn off caching -->\r\n    <meta");

WriteLiteral(" http-equiv=\"cache-control\"");

WriteLiteral(" content=\"max-age=0\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"cache-control\"");

WriteLiteral(" content=\"no-cache\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"expires\"");

WriteLiteral(" content=\"0\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"expires\"");

WriteLiteral(" content=\"Tue, 01 Jan 1980 1:00:00 GMT\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"pragma\"");

WriteLiteral(" content=\"no-cache\"");

WriteLiteral(" />\r\n    \r\n\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(Styles.Render("~/content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 36 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(Scripts.Render("~/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(Html.BudgetOnlineWeb().ProgressIndicator().BackgroundUrl(@Url.Content("~/Content/images/back1.jpg")).IndicatorUrl(@Url.Content("~/Content/images/ajax-loader.gif")).Class("progress-indicator").Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" id=\"container\"");

WriteLiteral(">\r\n        ");

WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"row nav-offset\"");

WriteLiteral(">\r\n");

            
            #line 56 "..\..\Views\Shared\_LayoutMain.cshtml"
            
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\_LayoutMain.cshtml"
              Html.RenderPartial("~/Views/Shared/TopNavligationMenu.cshtml");
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 60 "..\..\Views\Shared\_LayoutMain.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12 text-muted\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    &copy; Company ");

            
            #line 66 "..\..\Views\Shared\_LayoutMain.cshtml"
                              Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    \r\n    <div data-ng-view" +
"");

WriteLiteral(" class=\"shuffle-animation\"");

WriteLiteral("></div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 73 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(Scripts.Render("~/js2"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 74 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(Scripts.Render("~/angularApp"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 76 "..\..\Views\Shared\_LayoutMain.cshtml"
Write(RenderSection("Header", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
