#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\PeriodTypes\List.cshtml"
    using BudgetOnline.Web.Areas.Admin.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/PeriodTypes/List.cshtml")]
    public partial class _Areas_Admin_Views_PeriodTypes_List_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<PeriodTypeListViewModel>>
    {
        public _Areas_Admin_Views_PeriodTypes_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\PeriodTypes\List.cshtml"
  
    ViewBag.Title = "Периоды";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\PeriodTypes\List.cshtml"
Write(Html.BudgetOnlineWeb().PrimaryButton().Caption("Новая запись").RedirectTo(Url.Action("create")).Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\PeriodTypes\List.cshtml"
Write(Html.BudgetOnlineWeb()
    .Table<PeriodTypeListViewModel>()
    .Css("table table-striped")
    .Rows(Model)
    .Columns(columns =>
                {
                    columns.Icon().IconCss(m => m.IsDisabled ? "glyphicon-lock" : "").Span(1);
                    columns.Bound(m => m.Name).Span(9);
                    columns.Commands().Cell(m => m.Commands).Span(2);
                })
    .Build()
    );

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
