<?xml version="1.0" encoding="utf-8"?>
<Database Name="Budget" EntityNamespace="BudgetOnline.Data.MSSQL" ContextNamespace="BudgetOnline.Data.MSSQL" Class="BudgetOnlineDBDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="ShowForIncome" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowForOutcome" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowForTransfer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Icon" Type="System.String" DbType="NChar(512)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsExternal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Accounts_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_CategoryTemplates_Accounts_From" Member="CategoryTemplates" ThisKey="Id" OtherKey="FromAccountId" Type="CategoryTemplate" DeleteRule="NO ACTION" />
      <Association Name="FK_CategoryTemplates_Accounts_To" Member="CategoryTemplates_Accounts_Tos" ThisKey="Id" OtherKey="ToAccountId" Type="CategoryTemplate" DeleteRule="NO ACTION" />
      <Association Name="FK_PlannedTransactions_Accounts" Member="PlannedTransactions" ThisKey="Id" OtherKey="AccountId" Type="PlannedTransaction" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_Accounts" Member="TransactionGroups" ThisKey="Id" OtherKey="FromAccountId" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_Accounts1" Member="TransactionGroups_Accounts1s" ThisKey="Id" OtherKey="ToAccountId" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_Accounts" Member="Transactions" ThisKey="Id" OtherKey="AccountId" Type="Transaction" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Icon" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Categories_Categories" Member="Parent" ThisKey="ParentId" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="FK_Categories_Categories" Member="Categories_Categories" ThisKey="Id" OtherKey="ParentId" Type="Category" DeleteRule="NO ACTION" />
      <Association Name="FK_Categories_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_Categories_Users" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_PlannedTransactions_Categories" Member="PlannedTransactions" ThisKey="Id" OtherKey="CategoryId" Type="PlannedTransaction" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_Categories" Member="TransactionGroups" ThisKey="Id" OtherKey="CategoryId" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_Categories" Member="Transactions" ThisKey="Id" OtherKey="CategoryId" Type="Transaction" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryTemplates" Member="CategoryTemplates">
    <Type Name="CategoryTemplate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FromAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ToAccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_CategoryTemplates_Accounts_From" Member="Account" ThisKey="FromAccountId" OtherKey="Id" Type="Account" IsForeignKey="true" />
      <Association Name="FK_CategoryTemplates_Accounts_To" Member="ToAccount" ThisKey="ToAccountId" OtherKey="Id" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currencies" Member="Currencies">
    <Type Name="Currency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Symbol" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Currencies_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_CurrencyRates_Currencies" Member="CurrencyRates" ThisKey="Id" OtherKey="BaseCurrencyId" Type="CurrencyRate" DeleteRule="NO ACTION" />
      <Association Name="FK_CurrencyRates_Currencies1" Member="CurrencyRates_Currencies1s" ThisKey="Id" OtherKey="TargetCurrencyId" Type="CurrencyRate" DeleteRule="NO ACTION" />
      <Association Name="FK_PlannedTransactions_Currencies" Member="PlannedTransactions" ThisKey="Id" OtherKey="CurrencyId" Type="PlannedTransaction" DeleteRule="NO ACTION" />
      <Association Name="FK_StatisticsTotalOnDateDetails_Currencies" Member="StatisticsTotalOnDateDetails" ThisKey="Id" OtherKey="CurrencyId" Type="StatisticsTotalOnDateDetail" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_Currencies" Member="TransactionGroups" ThisKey="Id" OtherKey="ToCurrencyId" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_Currencies1" Member="TransactionGroups_Currencies1s" ThisKey="Id" OtherKey="FromCurrencyId" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_Currencies" Member="Transactions" ThisKey="Id" OtherKey="CurrencyId" Type="Transaction" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.CurrencyRates" Member="CurrencyRates">
    <Type Name="CurrencyRate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="BaseCurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetCurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_CurrencyRates_Currencies" Member="Currency" ThisKey="BaseCurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="FK_CurrencyRates_Currencies1" Member="TargetCurrency" ThisKey="TargetCurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="FK_CurrencyRates_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_CurrencyRates_Users" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_CurrencyRates_Users1" Member="UpdatedByUser" ThisKey="UpdatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DateTitles" Member="DateTitles">
    <Type Name="DateTitle">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_DateTitles_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_DateTitles_Users_CreatedBy" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_DateTitles_Users_UpdatedBy" Member="UpdatedByUser" ThisKey="UpdatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Directions" Member="Directions">
    <Type Name="Direction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Sign" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PeriodTypes" Member="PeriodTypes">
    <Type Name="PeriodType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Hours" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Days" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Weeks" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="WorkingDays" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Monthes" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Quarters" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Years" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="FK_PlannedTransactions_PeriodTypes" Member="PlannedTransactions" ThisKey="Id" OtherKey="PeriodTypeId" Type="PlannedTransaction" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.Permissions" Member="Permissions">
    <Type Name="Permission">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Association Name="FK_UserPermissions_Permissions" Member="UserPermissions" ThisKey="Id" OtherKey="PermissionId" Type="UserPermission" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.PlannedTransactions" Member="PlannedTransactions">
    <Type Name="PlannedTransaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PeriodTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Sum" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_PlannedTransactions_Accounts" Member="Account" ThisKey="AccountId" OtherKey="Id" Type="Account" IsForeignKey="true" />
      <Association Name="FK_PlannedTransactions_Categories" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="FK_PlannedTransactions_Currencies" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="FK_PlannedTransactions_PeriodTypes" Member="PeriodType" ThisKey="PeriodTypeId" OtherKey="Id" Type="PeriodType" IsForeignKey="true" />
      <Association Name="FK_PlannedTransactions_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_PlannedTransactions_TransactionTypes" Member="TransactionType" ThisKey="TransactionTypeId" OtherKey="Id" Type="TransactionType" IsForeignKey="true" />
      <Association Name="FK_PlannedTransactions_Users" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_PlannedTransactions_Users_Updated" Member="UpdatedByUser" ThisKey="UpdatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SectionAdmins" Member="SectionAdmins">
    <Type Name="SectionAdmin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BlockedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="BlockedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_SectionAdmins_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_SectionAdmins_Users" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sections" Member="Sections">
    <Type Name="Section">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Accounts_Sections" Member="Accounts" ThisKey="Id" OtherKey="SectionId" Type="Account" DeleteRule="NO ACTION" />
      <Association Name="FK_Categories_Sections" Member="Categories" ThisKey="Id" OtherKey="SectionId" Type="Category" DeleteRule="NO ACTION" />
      <Association Name="FK_Currencies_Sections" Member="Currencies" ThisKey="Id" OtherKey="SectionId" Type="Currency" DeleteRule="NO ACTION" />
      <Association Name="FK_CurrencyRates_Sections" Member="CurrencyRates" ThisKey="Id" OtherKey="SectionId" Type="CurrencyRate" DeleteRule="NO ACTION" />
      <Association Name="FK_DateTitles_Sections" Member="DateTitles" ThisKey="Id" OtherKey="SectionId" Type="DateTitle" DeleteRule="NO ACTION" />
      <Association Name="FK_PlannedTransactions_Sections" Member="PlannedTransactions" ThisKey="Id" OtherKey="SectionId" Type="PlannedTransaction" DeleteRule="NO ACTION" />
      <Association Name="FK_SectionAdmins_Sections" Member="SectionAdmins" ThisKey="Id" OtherKey="SectionId" Type="SectionAdmin" DeleteRule="NO ACTION" />
      <Association Name="FK_Settings_Sections" Member="Settings" ThisKey="Id" OtherKey="SectionId" Type="Setting" DeleteRule="NO ACTION" />
      <Association Name="FK_StatisticsTotalOnDates_Sections" Member="StatisticsTotalOnDates" ThisKey="Id" OtherKey="SectionId" Type="StatisticsTotalOnDate" DeleteRule="NO ACTION" />
      <Association Name="FK_Tags_Sections" Member="Tags" ThisKey="Id" OtherKey="SectionId" Type="Tag" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_Sections" Member="TransactionGroups" ThisKey="Id" OtherKey="SectionId" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_Sections" Member="Transactions" ThisKey="Id" OtherKey="SectionId" Type="Transaction" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionTags_Sections" Member="TransactionTags" ThisKey="Id" OtherKey="SectionId" Type="TransactionTag" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Settings_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_Settings_Users" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StatisticsTotalOnDateDetails" Member="StatisticsTotalOnDateDetails">
    <Type Name="StatisticsTotalOnDateDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TotalOnDateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sum" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="FK_StatisticsTotalOnDateDetails_Currencies" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="FK_StatisticsTotalOnDateDetails_StatisticsTotalOnDates" Member="StatisticsTotalOnDate" ThisKey="TotalOnDateId" OtherKey="Id" Type="StatisticsTotalOnDate" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StatisticsTotalOnDates" Member="StatisticsTotalOnDates">
    <Type Name="StatisticsTotalOnDate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalOnDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_StatisticsTotalOnDateDetails_StatisticsTotalOnDates" Member="StatisticsTotalOnDateDetails" ThisKey="Id" OtherKey="TotalOnDateId" Type="StatisticsTotalOnDateDetail" DeleteRule="NO ACTION" />
      <Association Name="FK_StatisticsTotalOnDates_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_StatisticsTotalOnDates_Users" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Hits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Tags_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_Tags_Users_Created" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_Tags_Users_Updated" Member="UpdatedByUser" ThisKey="UpdatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_TransactionTags_Tags" Member="TransactionTags" ThisKey="Id" OtherKey="TagId" Type="TransactionTag" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionGroups" Member="TransactionGroups">
    <Type Name="TransactionGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ToAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromSum" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ToSum" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FromCurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ToCurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_TransactionGroups_Accounts" Member="Account" ThisKey="FromAccountId" OtherKey="Id" Type="Account" IsForeignKey="true" />
      <Association Name="FK_TransactionGroups_Accounts1" Member="ToAccount" ThisKey="ToAccountId" OtherKey="Id" Type="Account" IsForeignKey="true" />
      <Association Name="FK_TransactionGroups_Categories" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="FK_TransactionGroups_Currencies" Member="Currency" ThisKey="ToCurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="FK_TransactionGroups_Currencies1" Member="FromCurrency" ThisKey="FromCurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="FK_TransactionGroups_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_TransactionGroups_TransactionTypes" Member="TransactionType" ThisKey="TransactionTypeId" OtherKey="Id" Type="TransactionType" IsForeignKey="true" />
      <Association Name="FK_TransactionGroups_Users" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_TransactionGroups_Users1" Member="UpdatedByUser" ThisKey="UpdatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_Transactions_TransactionGroups" Member="Transactions" ThisKey="Id" OtherKey="TransactionGroupId" Type="Transaction" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionLinks" Member="TransactionLinks">
    <Type Name="TransactionLink">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_TransactionLinks_Transactions_Child" Member="Transaction" ThisKey="ChildId" OtherKey="Id" Type="Transaction" IsForeignKey="true" />
      <Association Name="FK_TransactionLinks_Transactions_Parent" Member="Parent" ThisKey="ParentId" OtherKey="Id" Type="Transaction" IsForeignKey="true" />
      <Association Name="FK_TransactionLinks_Users" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LinkedId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LinkedAsParent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Sum" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Formula" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IsNotForStatistics" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_TransactionLinks_Transactions_Child" Member="TransactionLinks" ThisKey="Id" OtherKey="ChildId" Type="TransactionLink" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionLinks_Transactions_Parent" Member="TransactionLinks_Transactions_Parents" ThisKey="Id" OtherKey="ParentId" Type="TransactionLink" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_Accounts" Member="Account" ThisKey="AccountId" OtherKey="Id" Type="Account" IsForeignKey="true" />
      <Association Name="FK_Transactions_Categories" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="FK_Transactions_Currencies" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="FK_Transactions_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_Transactions_TransactionGroups" Member="TransactionGroup" ThisKey="TransactionGroupId" OtherKey="Id" Type="TransactionGroup" IsForeignKey="true" />
      <Association Name="FK_Transactions_Transactions_LinkedId" Member="Linked" ThisKey="LinkedId" OtherKey="Id" Type="Transaction" IsForeignKey="true" />
      <Association Name="FK_Transactions_Transactions_LinkedId" Member="Transactions_Transactions_LinkedIds" ThisKey="Id" OtherKey="LinkedId" Type="Transaction" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_TransactionTypes" Member="TransactionType" ThisKey="TransactionTypeId" OtherKey="Id" Type="TransactionType" IsForeignKey="true" />
      <Association Name="FK_Transactions_Users_CreatedBy" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_Transactions_Users_Updated" Member="UpdatedByUser" ThisKey="UpdatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_TransactionTags_Transactions" Member="TransactionTags" ThisKey="Id" OtherKey="TransactionId" Type="TransactionTag" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionTags" Member="TransactionTags">
    <Type Name="TransactionTag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_TransactionTags_Sections" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
      <Association Name="FK_TransactionTags_Tags" Member="TransactionTags_Tag" ThisKey="TagId" OtherKey="Id" Type="Tag" IsForeignKey="true" />
      <Association Name="FK_TransactionTags_Transactions" Member="Transaction" ThisKey="TransactionId" OtherKey="Id" Type="Transaction" IsForeignKey="true" DeleteOnNull="true" />
      <Association Name="FK_TransactionTags_Users_Created" Member="User" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_TransactionTags_Users_Updated" Member="UpdatedByUser" ThisKey="UpdatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionTypes" Member="TransactionTypes">
    <Type Name="TransactionType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Association Name="FK_PlannedTransactions_TransactionTypes" Member="PlannedTransactions" ThisKey="Id" OtherKey="TransactionTypeId" Type="PlannedTransaction" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_TransactionTypes" Member="TransactionGroups" ThisKey="Id" OtherKey="TransactionTypeId" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_TransactionTypes" Member="Transactions" ThisKey="Id" OtherKey="TransactionTypeId" Type="Transaction" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.UserConnects" Member="UserConnects">
    <Type Name="UserConnect">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserConnectStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserPasswordId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Origin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ExpiresWhen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FK_UserConnects_UserPasswords" Member="UserPassword" ThisKey="UserPasswordId" OtherKey="Id" Type="UserPassword" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserConnectStatuses" Member="UserConnectStatuses">
    <Type Name="UserConnectStatuse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserPasswords" Member="UserPasswords">
    <Type Name="UserPassword">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MemoriableWord" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_UserConnects_UserPasswords" Member="UserConnects" ThisKey="Id" OtherKey="UserPasswordId" Type="UserConnect" DeleteRule="NO ACTION" />
      <Association Name="FK_UserPasswords_Users" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserPermissions" Member="UserPermissions">
    <Type Name="UserPermission">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FK_UserPermissions_Permissions" Member="Permission" ThisKey="PermissionId" OtherKey="Id" Type="Permission" IsForeignKey="true" />
      <Association Name="FK_UserPermissions_Users" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="FK_UserPermissions_Users1" Member="CreatedByUser" ThisKey="CreatedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Culture" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IsDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsForsePassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedWhen" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedWhen" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Categories_Users" Member="Categories" ThisKey="Id" OtherKey="CreatedBy" Type="Category" DeleteRule="NO ACTION" />
      <Association Name="FK_CurrencyRates_Users" Member="CurrencyRates" ThisKey="Id" OtherKey="CreatedBy" Type="CurrencyRate" DeleteRule="NO ACTION" />
      <Association Name="FK_CurrencyRates_Users1" Member="CurrencyRates_Users1s" ThisKey="Id" OtherKey="UpdatedBy" Type="CurrencyRate" DeleteRule="NO ACTION" />
      <Association Name="FK_DateTitles_Users_CreatedBy" Member="DateTitles" ThisKey="Id" OtherKey="CreatedBy" Type="DateTitle" DeleteRule="NO ACTION" />
      <Association Name="FK_DateTitles_Users_UpdatedBy" Member="DateTitles_Users_UpdatedBies" ThisKey="Id" OtherKey="UpdatedBy" Type="DateTitle" DeleteRule="NO ACTION" />
      <Association Name="FK_PlannedTransactions_Users" Member="PlannedTransactions" ThisKey="Id" OtherKey="CreatedBy" Type="PlannedTransaction" DeleteRule="NO ACTION" />
      <Association Name="FK_PlannedTransactions_Users_Updated" Member="PlannedTransactions_Users_Updateds" ThisKey="Id" OtherKey="UpdatedBy" Type="PlannedTransaction" DeleteRule="NO ACTION" />
      <Association Name="FK_SectionAdmins_Users" Member="SectionAdmins" ThisKey="Id" OtherKey="UserId" Type="SectionAdmin" DeleteRule="NO ACTION" />
      <Association Name="FK_Settings_Users" Member="Settings" ThisKey="Id" OtherKey="UserId" Type="Setting" DeleteRule="NO ACTION" />
      <Association Name="FK_StatisticsTotalOnDates_Users" Member="StatisticsTotalOnDates" ThisKey="Id" OtherKey="CreatedBy" Type="StatisticsTotalOnDate" DeleteRule="NO ACTION" />
      <Association Name="FK_Tags_Users_Created" Member="Tags" ThisKey="Id" OtherKey="CreatedBy" Type="Tag" DeleteRule="NO ACTION" />
      <Association Name="FK_Tags_Users_Updated" Member="Tags_Users_Updateds" ThisKey="Id" OtherKey="UpdatedBy" Type="Tag" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_Users" Member="TransactionGroups" ThisKey="Id" OtherKey="CreatedBy" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionGroups_Users1" Member="TransactionGroups_Users1s" ThisKey="Id" OtherKey="UpdatedBy" Type="TransactionGroup" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionLinks_Users" Member="TransactionLinks" ThisKey="Id" OtherKey="CreatedBy" Type="TransactionLink" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_Users_CreatedBy" Member="Transactions" ThisKey="Id" OtherKey="CreatedBy" Type="Transaction" DeleteRule="NO ACTION" />
      <Association Name="FK_Transactions_Users_Updated" Member="Transactions_Users_Updateds" ThisKey="Id" OtherKey="UpdatedBy" Type="Transaction" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionTags_Users_Created" Member="TransactionTags" ThisKey="Id" OtherKey="CreatedBy" Type="TransactionTag" DeleteRule="NO ACTION" />
      <Association Name="FK_TransactionTags_Users_Updated" Member="TransactionTags_Users_Updateds" ThisKey="Id" OtherKey="UpdatedBy" Type="TransactionTag" DeleteRule="NO ACTION" />
      <Association Name="FK_UserPasswords_Users" Member="UserPasswords" ThisKey="Id" OtherKey="UserId" Type="UserPassword" DeleteRule="NO ACTION" />
      <Association Name="FK_UserPermissions_Users" Member="UserPermissions" ThisKey="Id" OtherKey="UserId" Type="UserPermission" DeleteRule="NO ACTION" />
      <Association Name="FK_UserPermissions_Users1" Member="UserPermissions_Users1s" ThisKey="Id" OtherKey="CreatedBy" Type="UserPermission" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="dbo.UserSettings" Member="UserSettings">
    <Type Name="UserSetting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="DefaultValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>