#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\AlertSuccess.cshtml"
    using BudgetOnline.UI.Helpers;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\AlertSuccess.cshtml"
    using BudgetOnline.UI.Models.Alerts;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class AlertSuccess : System.Web.WebPages.HelperPage
    {

#line 9 "..\..\Views\AlertSuccess.cshtml"
public static System.Web.WebPages.HelperResult Render(AlertSuccessModel model)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 10 "..\..\Views\AlertSuccess.cshtml"
 
    var id = string.IsNullOrWhiteSpace(model.Name) ? UIHelper.GenerateRandomCode(10) : model.Name;
    


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"alert alert-success\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 326), Tuple.Create("\"", 334)

#line 13 "..\..\Views\AlertSuccess.cshtml"
, Tuple.Create(Tuple.Create("", 331), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 331), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 14 "..\..\Views\AlertSuccess.cshtml"
        

#line default
#line hidden

#line 14 "..\..\Views\AlertSuccess.cshtml"
         if (!model.IsForbidClose)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <button");

WriteLiteralTo(__razor_helper_writer, " data-dismiss=\"alert\"");

WriteLiteralTo(__razor_helper_writer, " class=\"close\"");

WriteLiteralTo(__razor_helper_writer, " type=\"button\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                ×</button>\t\r\n");


#line 18 "..\..\Views\AlertSuccess.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");


#line 19 "..\..\Views\AlertSuccess.cshtml"
         if (!string.IsNullOrWhiteSpace(model.MessageSuffix))
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <strong>");


#line 21 "..\..\Views\AlertSuccess.cshtml"
WriteTo(__razor_helper_writer, model.MessageSuffix);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</strong> \r\n");


#line 22 "..\..\Views\AlertSuccess.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");


#line 23 "..\..\Views\AlertSuccess.cshtml"
WriteTo(__razor_helper_writer, new HtmlString(model.Message));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n    </div>\r\n");


#line 25 "..\..\Views\AlertSuccess.cshtml"


#line default
#line hidden
});

#line 25 "..\..\Views\AlertSuccess.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
