#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\DateEditBox.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\DateEditBox.cshtml"
    using BudgetOnline.UI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DateEditBox.cshtml")]
    public partial class DateEditBox : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 4 "..\..\Views\DateEditBox.cshtml"


        #line default
        #line hidden

public System.Web.WebPages.HelperResult Render(DateEditModel model) 
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Views\DateEditBox.cshtml"
 
    var id = string.IsNullOrWhiteSpace(model.Name) ? Html.GetUniqId(10) : model.Name;
    var value = model.Date.HasValue ? model.Date.Value.ToLocalTime().ToShortDateString() : string.Empty;
    

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"input-group ");



#line 11 "..\..\Views\DateEditBox.cshtml"
WriteTo(@__razor_helper_writer, model.Span > 0 ? "col-md-" + model.Span.ToString(CultureInfo.InvariantCulture) : string.Empty);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"> \r\n        <input type=\"text\" name=\"");



#line 12 "..\..\Views\DateEditBox.cshtml"
  WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 12 "..\..\Views\DateEditBox.cshtml"
              WriteTo(@__razor_helper_writer, value);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" class=\"date-picker form-control\" autocomplete=\"off\"/>\r\n        <span class=\"inp" +
"ut-group-addon\"><i class=\"glyphicon glyphicon-calendar\"></i></span>\r\n    </div>\r" +
"\n");



#line 15 "..\..\Views\DateEditBox.cshtml"

#line default
#line hidden

});

}


        public DateEditBox()
        {
        }
        public override void Execute()
        {




WriteLiteral("\r\n");


WriteLiteral("\r\n");




        }
    }
}
#pragma warning restore 1591
