#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\MenuItemWithActions.cshtml"
    using BudgetOnline.UI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MenuItemWithActions.cshtml")]
    public partial class _Views_MenuItemWithActions_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 3 "..\..\Views\MenuItemWithActions.cshtml"
            

        #line default
        #line hidden

#line 6 "..\..\Views\MenuItemWithActions.cshtml"
public System.Web.WebPages.HelperResult Render(PaginationModel model)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 7 "..\..\Views\MenuItemWithActions.cshtml"
 
    var id = string.IsNullOrWhiteSpace(model.Name) ? Html.GetUniqId(10) : model.Name;



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\t<li");

WriteLiteralTo(__razor_helper_writer, " class=\"dropdown\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t<a");

WriteLiteralTo(__razor_helper_writer, " data-toggle=\"dropdown\"");

WriteLiteralTo(__razor_helper_writer, " class=\"dropdown-toggle\"");

WriteLiteralTo(__razor_helper_writer, " href=\"#\"");

WriteLiteralTo(__razor_helper_writer, ">Title <b");

WriteLiteralTo(__razor_helper_writer, " class=\"caret\"");

WriteLiteralTo(__razor_helper_writer, "></b></a>\r\n\t\t<ul");

WriteLiteralTo(__razor_helper_writer, " class=\"dropdown-menu\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t\t<li><a");

WriteLiteralTo(__razor_helper_writer, " href=\"#\"");

WriteLiteralTo(__razor_helper_writer, ">Action</a></li>\r\n\t\t\t<li><a");

WriteLiteralTo(__razor_helper_writer, " href=\"#\"");

WriteLiteralTo(__razor_helper_writer, ">Another action</a></li>\r\n\t\t\t<li><a");

WriteLiteralTo(__razor_helper_writer, " href=\"#\"");

WriteLiteralTo(__razor_helper_writer, ">Something else here</a></li>\r\n\t\t\t<li");

WriteLiteralTo(__razor_helper_writer, " class=\"divider\"");

WriteLiteralTo(__razor_helper_writer, "></li>\r\n\t\t\t");

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t");

WriteLiteralTo(__razor_helper_writer, "\r\n\t\t\t<li><a");

WriteLiteralTo(__razor_helper_writer, " href=\"#\"");

WriteLiteralTo(__razor_helper_writer, ">One more separated link</a></li>\r\n\t\t</ul>\r\n\t</li>\r\n");


#line 22 "..\..\Views\MenuItemWithActions.cshtml"


#line default
#line hidden
});

#line 22 "..\..\Views\MenuItemWithActions.cshtml"
}
#line default
#line hidden

        public _Views_MenuItemWithActions_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
