#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Paginator.cshtml"
    using BudgetOnline.UI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Paginator.cshtml")]
    public partial class Paginator : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 3 "..\..\Views\Paginator.cshtml"


        #line default
        #line hidden

public System.Web.WebPages.HelperResult Render(PaginationModel model)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Views\Paginator.cshtml"
 
        var id = string.IsNullOrWhiteSpace(model.Name) ? Html.GetUniqId(10) : model.Name;
        var pages = model.GetPages();
    

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"pagination pagination-small pagination-centered\">\r\n        <ul>\r\n" +
"            <li><a href=\"");



#line 12 "..\..\Views\Paginator.cshtml"
WriteTo(@__razor_helper_writer, Html.GetUrlQithNewQueryParameter("page", "1"));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">«</a></li>\r\n");



#line 13 "..\..\Views\Paginator.cshtml"
             foreach (var page in pages)
            {
                if (model.Page == page)
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <li class=\"active\"><a href=\"#\">");



#line 17 "..\..\Views\Paginator.cshtml"
                WriteTo(@__razor_helper_writer, page);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a></li>\r\n");



#line 18 "..\..\Views\Paginator.cshtml"
                }
                else
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <li><a href=\"");



#line 21 "..\..\Views\Paginator.cshtml"
WriteTo(@__razor_helper_writer, Html.GetUrlQithNewQueryParameter("page", @page.ToString()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 21 "..\..\Views\Paginator.cshtml"
                                                           WriteTo(@__razor_helper_writer, page);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a></li>\r\n");



#line 22 "..\..\Views\Paginator.cshtml"
                }
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <li><a href=\"");



#line 24 "..\..\Views\Paginator.cshtml"
WriteTo(@__razor_helper_writer, Html.GetUrlQithNewQueryParameter("page", model.PagesCount.ToString()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">»</a></li>\r\n        </ul>\r\n    </div>\r\n");



#line 27 "..\..\Views\Paginator.cshtml"

#line default
#line hidden

});

}


        public Paginator()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


WriteLiteral("\r\n");




        }
    }
}
#pragma warning restore 1591
