#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Paginator.cshtml"
    using BudgetOnline.UI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Paginator.cshtml")]
    public partial class Paginator : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 3 "..\..\Views\Paginator.cshtml"


        #line default
        #line hidden

public System.Web.WebPages.HelperResult Render(PaginationModel model)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Views\Paginator.cshtml"
     
        var id = string.IsNullOrWhiteSpace(model.Name) ? Html.GetUniqId(10) : model.Name;
        var pages = model.GetPages();
        var nextPageSize = model.PageSizes.FirstOrDefault(p => p > model.PageSize);
        if (nextPageSize == 0)
        {
            nextPageSize = model.PageSizes[0];
        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"visible-xs clearfix\" style=\"height: 10px\">\r\n    </div>\r\n");



WriteLiteralTo(@__razor_helper_writer, "    <div class=\"row-fluid\">\r\n        <div class=\"col-md-5 col-md-offset-4 col-sm-" +
"4 col-sm-offset-2\">\r\n            <ul class=\"pagination pagination-sm pull-left\">" +
"\r\n                <li><a href=\"");



#line 19 "..\..\Views\Paginator.cshtml"
WriteTo(@__razor_helper_writer, Html.GetUrlQithNewQueryParameter("page", "1"));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">«</a></li>\r\n");



#line 20 "..\..\Views\Paginator.cshtml"
                 foreach (var page in pages)
                {
                    if (model.Page == page)
                    {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    <li class=\"active\"><a href=\"#\">");



#line 24 "..\..\Views\Paginator.cshtml"
                    WriteTo(@__razor_helper_writer, page);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a></li>\r\n");



#line 25 "..\..\Views\Paginator.cshtml"
                    }
                    else
                    {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    <li><a href=\"");



#line 28 "..\..\Views\Paginator.cshtml"
  WriteTo(@__razor_helper_writer, Html.GetUrlQithNewQueryParameter("page", @page.ToString()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 28 "..\..\Views\Paginator.cshtml"
                                                               WriteTo(@__razor_helper_writer, page);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a></li>\r\n");



#line 29 "..\..\Views\Paginator.cshtml"
                    }
                }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <li><a href=\"");



#line 31 "..\..\Views\Paginator.cshtml"
WriteTo(@__razor_helper_writer, Html.GetUrlQithNewQueryParameter("page", model.PagesCount.ToString()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, @""">
                    »</a></li>
            </ul>
        </div>
        <div class=""col-md-3 col-sm-6"">
            <div style=""margin-top: 10px"" class=""pull-right"">
                <label class="""">
                    Страница:
                </label>
                <div class=""btn-group"">
                    <button class=""btn btn-default btn-xs dropdown-toggle"" data-toggle=""dropdown"" href=""");



#line 41 "..\..\Views\Paginator.cshtml"
                                                                         WriteTo(@__razor_helper_writer, Html.GetUrlQithNewQueryParameter("pageSize", nextPageSize.ToString()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n                        ");



#line 42 "..\..\Views\Paginator.cshtml"
WriteTo(@__razor_helper_writer, model.PageSize);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&nbsp;&nbsp;&nbsp; <span class=\"caret\"></span>\r\n                    </button>\r\n  " +
"                  <ul class=\"dropdown-menu\" id=\"setPageSize\">\r\n");



#line 45 "..\..\Views\Paginator.cshtml"
                         foreach (var pageSize in model.PageSizes)
                        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                            <li><a href=\"");



#line 47 "..\..\Views\Paginator.cshtml"
          WriteTo(@__razor_helper_writer, Html.GetUrlQithNewQueryParameter("pageSize", pageSize.ToString()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 47 "..\..\Views\Paginator.cshtml"
                                                                              WriteTo(@__razor_helper_writer, pageSize);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a></li>\r\n");



#line 48 "..\..\Views\Paginator.cshtml"
                        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    </ul>\r\n                </div>\r\n            </div>\r\n        </" +
"div>\r\n    </div>\r\n");



WriteLiteralTo(@__razor_helper_writer, "    <div class=\"clearfix\">\r\n    </div>\r\n");



WriteLiteralTo(@__razor_helper_writer, "    <div class=\"\" style=\"height: 10px\">\r\n    </div>\r\n");



#line 58 "..\..\Views\Paginator.cshtml"

#line default
#line hidden

});

}


        public Paginator()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


WriteLiteral("\r\n");




        }
    }
}
#pragma warning restore 1591
