#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\ProgressIndicator.cshtml"
    using BudgetOnline.UI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ProgressIndicator.cshtml")]
    public partial class ProgressIndicator : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 3 "..\..\Views\ProgressIndicator.cshtml"


        #line default
        #line hidden

public System.Web.WebPages.HelperResult Render(ProgressIndicatorModel model)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Views\ProgressIndicator.cshtml"
     
        var id = string.IsNullOrWhiteSpace(model.Name) ? Html.GetUniqId(10) : model.Name;
    

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div id=\"");



#line 9 "..\..\Views\ProgressIndicator.cshtml"
WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" style=\"width: 100px; height: 100px; position: absolute; z-index: 998;\" class=\"h" +
"idden ");



#line 9 "..\..\Views\ProgressIndicator.cshtml"
                                                                         WriteTo(@__razor_helper_writer, model.Class);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n        <div style=\"background-image: url(");



#line 10 "..\..\Views\ProgressIndicator.cshtml"
            WriteTo(@__razor_helper_writer, model.IndicatorUrl);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, @");background-position: center center; background-repeat: no-repeat; position: absolute; left: 0; top: 0; width: 100%;z-index: 999; 
                                                                              	height: 100%;"">
		</div>
        <div style=""background-image: url(");



#line 13 "..\..\Views\ProgressIndicator.cshtml"
            WriteTo(@__razor_helper_writer, model.BackgroundUrl);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "); opacity: .75; width: 100%;z-index: 998; \r\n \t              \t                \the" +
"ight: 100%;\">\r\n        </div>\r\n    </div>\r\n");



#line 17 "..\..\Views\ProgressIndicator.cshtml"
            

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <script type=\"text/javascript\" language=\"javascript\"><!--\r\n        //\t\t$(func" +
"tion () {\r\n        //\t\t});\r\n\t\t//-->\r\n    </script>\r\n");



#line 23 "..\..\Views\ProgressIndicator.cshtml"

#line default
#line hidden

});

}


        public ProgressIndicator()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


WriteLiteral("\r\n");



WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
