#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\ProgressIndicator.cshtml"
    using BudgetOnline.UI.Helpers;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\ProgressIndicator.cshtml"
    using BudgetOnline.UI.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class ProgressIndicator : System.Web.WebPages.HelperPage
    {

#line 9 "..\..\Views\ProgressIndicator.cshtml"
public static System.Web.WebPages.HelperResult Render(ProgressIndicatorModel model)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 10 "..\..\Views\ProgressIndicator.cshtml"
 
    var id = string.IsNullOrWhiteSpace(model.Name) ? UIHelper.GenerateRandomCode(10) : model.Name;



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 292), Tuple.Create("\"", 300)

#line 13 "..\..\Views\ProgressIndicator.cshtml"
, Tuple.Create(Tuple.Create("", 297), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 297), false)
);

WriteLiteralTo(__razor_helper_writer, " style=\"width: 100px; height: 100px; position: absolute; z-index: 998;\"");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 372), Tuple.Create("\"", 401)
, Tuple.Create(Tuple.Create("", 380), Tuple.Create("hidden", 380), true)

#line 13 "..\..\Views\ProgressIndicator.cshtml"
                        , Tuple.Create(Tuple.Create(" ", 386), Tuple.Create<System.Object, System.Int32>(model.Class

#line default
#line hidden
, 387), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteAttributeTo(__razor_helper_writer, "style", Tuple.Create(" style=\"", 417), Tuple.Create("\"", 612)
, Tuple.Create(Tuple.Create("", 425), Tuple.Create("background-image:", 425), true)
, Tuple.Create(Tuple.Create(" ", 442), Tuple.Create("url(", 443), true)

#line 14 "..\..\Views\ProgressIndicator.cshtml"
, Tuple.Create(Tuple.Create("", 447), Tuple.Create<System.Object, System.Int32>(model.IndicatorUrl

#line default
#line hidden
, 447), false)
, Tuple.Create(Tuple.Create("", 468), Tuple.Create(");background-position:", 468), true)
, Tuple.Create(Tuple.Create(" ", 490), Tuple.Create("center", 491), true)
, Tuple.Create(Tuple.Create(" ", 497), Tuple.Create("center;", 498), true)
, Tuple.Create(Tuple.Create(" ", 505), Tuple.Create("background-repeat:", 506), true)
, Tuple.Create(Tuple.Create(" ", 524), Tuple.Create("no-repeat;", 525), true)
, Tuple.Create(Tuple.Create(" ", 535), Tuple.Create("position:", 536), true)
, Tuple.Create(Tuple.Create(" ", 545), Tuple.Create("absolute;", 546), true)
, Tuple.Create(Tuple.Create(" ", 555), Tuple.Create("left:", 556), true)
, Tuple.Create(Tuple.Create(" ", 561), Tuple.Create("0;", 562), true)
, Tuple.Create(Tuple.Create(" ", 564), Tuple.Create("top:", 565), true)
, Tuple.Create(Tuple.Create(" ", 569), Tuple.Create("0;", 570), true)
, Tuple.Create(Tuple.Create(" ", 572), Tuple.Create("width:", 573), true)
, Tuple.Create(Tuple.Create(" ", 579), Tuple.Create("100%;z-index:", 580), true)
, Tuple.Create(Tuple.Create(" ", 593), Tuple.Create("999;", 594), true)
, Tuple.Create(Tuple.Create(" ", 598), Tuple.Create("height:", 599), true)
, Tuple.Create(Tuple.Create(" ", 606), Tuple.Create("100%;", 607), true)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n\t\t</div>\r\n        <div");

WriteAttributeTo(__razor_helper_writer, "style", Tuple.Create(" style=\"", 638), Tuple.Create("\"", 746)
, Tuple.Create(Tuple.Create("", 646), Tuple.Create("background-image:", 646), true)
, Tuple.Create(Tuple.Create(" ", 663), Tuple.Create("url(", 664), true)

#line 16 "..\..\Views\ProgressIndicator.cshtml"
, Tuple.Create(Tuple.Create("", 668), Tuple.Create<System.Object, System.Int32>(model.BackgroundUrl

#line default
#line hidden
, 668), false)
, Tuple.Create(Tuple.Create("", 690), Tuple.Create(");", 690), true)
, Tuple.Create(Tuple.Create(" ", 692), Tuple.Create("opacity:", 693), true)
, Tuple.Create(Tuple.Create(" ", 701), Tuple.Create(".75;", 702), true)
, Tuple.Create(Tuple.Create(" ", 706), Tuple.Create("width:", 707), true)
, Tuple.Create(Tuple.Create(" ", 713), Tuple.Create("100%;z-index:", 714), true)
, Tuple.Create(Tuple.Create(" ", 727), Tuple.Create("998;", 728), true)
, Tuple.Create(Tuple.Create(" ", 732), Tuple.Create("height:", 733), true)
, Tuple.Create(Tuple.Create(" ", 740), Tuple.Create("100%;", 741), true)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n        </div>\r\n    </div>\r\n");


#line 19 "..\..\Views\ProgressIndicator.cshtml"


#line default
#line hidden
});

#line 19 "..\..\Views\ProgressIndicator.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
