#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Editors\CurrencyBundle.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Views\Editors\CurrencyBundle.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Editors\CurrencyBundle.cshtml"
    using BudgetOnline.UI.PreCompiled.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Editors/CurrencyBundle.cshtml")]
    public partial class _Views_Editors_CurrencyBundle_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 4 "..\..\Views\Editors\CurrencyBundle.cshtml"
            

        #line default
        #line hidden

#line 6 "..\..\Views\Editors\CurrencyBundle.cshtml"
public System.Web.WebPages.HelperResult Render(BudgetOnline.UI.PreCompiled.Models.Editors.CurrencyBundle model, string propertyName, ModelState state, IDictionary<string, object> additionalValues)
    {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 7 "..\..\Views\Editors\CurrencyBundle.cshtml"
     
        var id = Html.GetUniqId(10);

        var placeholder = "";
        if (additionalValues.ContainsKey("placeholder"))
        {
            placeholder = additionalValues["placeholder"].ToString();
        }

        var value = model.Sum.ToString(CultureInfo.CurrentUICulture);

        var cssFormulaClass = " col-md-10 data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssFormulaClass += " input-validation-error";
        }

        var cssCurrencyListClass = " data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssCurrencyListClass += " input-validation-error";
        }

        var cssAccountListClass = " data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssAccountListClass += " input-validation-error";
        }



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1240), Tuple.Create("\"", 1248)

#line 36 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1245), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1245), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-4\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 39 "..\..\Views\Editors\CurrencyBundle.cshtml"
WriteTo(__razor_helper_writer, new _Views_Editors_SelectList_cshtml().Render(model.Account.Items, propertyName + ".Account", cssAccountListClass, false));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </div>\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-1\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            </div>\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-4\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group col-md-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 1703), Tuple.Create("\"", 1733)

#line 46 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1710), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 1710), false)
, Tuple.Create(Tuple.Create("", 1725), Tuple.Create(".Formula", 1725), true)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1734), Tuple.Create("\"", 1762)

#line 46 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1739), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 1739), false)
, Tuple.Create(Tuple.Create("", 1754), Tuple.Create("_Formula", 1754), true)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 1763), Tuple.Create("\"", 1787)

#line 46 "..\..\Views\Editors\CurrencyBundle.cshtml"
                               , Tuple.Create(Tuple.Create("", 1771), Tuple.Create<System.Object, System.Int32>(model.Formula

#line default
#line hidden
, 1771), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1788), Tuple.Create("\"", 1812)

#line 46 "..\..\Views\Editors\CurrencyBundle.cshtml"
                                                       , Tuple.Create(Tuple.Create("", 1796), Tuple.Create<System.Object, System.Int32>(cssFormulaClass

#line default
#line hidden
, 1796), false)
);

WriteLiteralTo(__razor_helper_writer, " autocomplete = \"off\" placeholder=\"");


#line 46 "..\..\Views\Editors\CurrencyBundle.cshtml"
                                                                                                                                                             WriteTo(__razor_helper_writer, placeholder);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"/>\r\n                        <span");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-comment\"");

WriteLiteralTo(__razor_helper_writer, "></i></span>\r\n                    </div>\r\n                </div>\r\n               " +
" <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group col-md-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 2159), Tuple.Create("\"", 2185)

#line 52 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 2166), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 2166), false)
, Tuple.Create(Tuple.Create("", 2181), Tuple.Create(".Sum", 2181), true)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 2186), Tuple.Create("\"", 2210)

#line 52 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 2191), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 2191), false)
, Tuple.Create(Tuple.Create("", 2206), Tuple.Create("_Sum", 2206), true)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 2211), Tuple.Create("\"", 2225)

#line 52 "..\..\Views\Editors\CurrencyBundle.cshtml"
                      , Tuple.Create(Tuple.Create("", 2219), Tuple.Create<System.Object, System.Int32>(value

#line default
#line hidden
, 2219), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"form-control input-sm calculator-result\"");

WriteLiteralTo(__razor_helper_writer, " readonly = \"readonly\" autocomplete = \"off\" title = \"Результат из поля Сумма\"/>\r\n" +
"                    </div>\r\n                </div>\r\n            </div>\r\n        " +
"    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-3\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 57 "..\..\Views\Editors\CurrencyBundle.cshtml"
WriteTo(__razor_helper_writer, new _Views_Editors_SelectList_cshtml().Render(model.Currency.Items, propertyName + ".Currency", cssCurrencyListClass, false));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <script");

WriteLiteralTo(__razor_helper_writer, " type=\"text/javascript\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        $(document).ready(function () {\r\n            turnOn_calculator(\'");


#line 63 "..\..\Views\Editors\CurrencyBundle.cshtml"
  WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n        });\r\n    </script>\r\n");


#line 66 "..\..\Views\Editors\CurrencyBundle.cshtml"


#line default
#line hidden
});

#line 66 "..\..\Views\Editors\CurrencyBundle.cshtml"
}
#line default
#line hidden

        public _Views_Editors_CurrencyBundle_cshtml()
        {
        }
        public override void Execute()
        {
        }
    }
}
#pragma warning restore 1591
