#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.ListViewCommands
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
    using BudgetOnline.UI.Models.ViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class JsViewCommand
    {
        
        #line 4 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"


        #line default
        #line hidden

public static System.Web.WebPages.HelperResult Render(ViewCommandUIModel command)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
     
        var jsCommand = command.Command as JsViewCommandModel;
        if (jsCommand == null)
        {
            throw new HttpException(404, "ViewCommand has invalid argument!");
        }
        var uid = Guid.NewGuid().ToString().Replace("-", "");
        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a id=\"js");



#line 15 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, uid);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" href=\"#\" title=\"");



#line 15 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, command.Title);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 15 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
          WebViewPage.WriteTo(@__razor_helper_writer, command.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <script type=\"text/javascript\">\r\n        $().ready(function() {\r\n\t\t\t$(\'a#js");



#line 18 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, uid);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\').click(\r\n\t\t\t\tfunction(e) {\r\n\t\t\t\t\te.preventDefault();\r\n");



#line 21 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
 					if (!string.IsNullOrWhiteSpace(jsCommand.Data))
     {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                        ");



#line 23 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, jsCommand.ClientFunction);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "(\"");



#line 23 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
          WebViewPage.WriteTo(@__razor_helper_writer, jsCommand.Data);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\");\r\n                    ");



#line 24 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
                           }
     else
     {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                        ");



#line 27 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, jsCommand.ClientFunction);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "();\r\n                    ");



#line 28 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"
                           }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t\t\t\t}\r\n\t\t\t);\r\n\t\t});\r\n\t\t\r\n    </script>\r\n");



#line 34 "..\..\Views\ListViewCommands\JsViewCommand.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
