#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.ListViewCommands
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
    using BudgetOnline.UI.Models.ViewCommands;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
    using BudgetOnline.UI.Views.ListViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class ListOfViewCommandUI
    {

public static System.Web.WebPages.HelperResult Render(IEnumerable<ViewCommandUIModel> commands)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 5 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
 
        if (commands == null || !commands.Any())
        {
        }
        else
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"btn-group\">\r\n");



#line 12 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
          
			var defaultCommand = commands.FirstOrDefault(o => o.IsDefault && o.Command.CommandType == CommandType.Redirect);
            if (defaultCommand != null)
            {
                
#line default
#line hidden


#line 16 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, ViewCommandUIDefault.Render(defaultCommand));

#line default
#line hidden


#line 16 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
                                                            
                
				
#line default
#line hidden



#line 18 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
                                                                                                                                                                                                          
            }
            else
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <a class=\"btn btn-mini\" href=\"\"><i class=\"icon-list\"></i><span st" +
"yle=\"padding-left: 1em\">Команды</span></a>\r\n");



#line 23 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
            }
        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <a class=\"btn btn-mini dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"><" +
"span class=\"caret\"></span></a>\r\n        <ul class=\"dropdown-menu\">\r\n");



#line 27 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
             foreach (var command in commands)
            {
                
#line default
#line hidden


#line 29 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, ViewCommandUI.Render(command, false));

#line default
#line hidden


#line 29 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
                                                     
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </ul>\r\n    </div>\r\n");



#line 33 "..\..\Views\ListViewCommands\ListOfViewCommandUI.cshtml"
        }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
