#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.ListViewCommands
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
    using BudgetOnline.UI.Models.ViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class PostViewCommand
    {
        
        #line 3 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"


        #line default
        #line hidden

public static System.Web.WebPages.HelperResult Render(ViewCommandUIModel command)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
     
        var postCommand = command.Command as PostViewCommandModel;
        if (postCommand == null)
        {
            throw new HttpException(404, "ViewCommand has invalid argument!");
        }

        var uid = Guid.NewGuid().ToString().Replace("-", "");
        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a id=\"post");



#line 15 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, uid);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" role=\"menuitem\" tabindex=\"-1\" href=\"#\" title=\"");



#line 15 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
                          WebViewPage.WriteTo(@__razor_helper_writer, command.Title);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 15 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
                                          WebViewPage.WriteTo(@__razor_helper_writer, command.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <script type=\"text/javascript\">\r\n        $().ready(function() {\r\n\t\t\t$(\'a#post" +
"");



#line 18 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, uid);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\').click(\r\n\t\t\t\tfunction(e) {\r\n\t\t\t        e.preventDefault();\r\n\t\t\t        $.postda" +
"tas({\r\n\t\t\t\t        url:\'");



#line 22 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, postCommand.Path);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\',\r\n\t\t\t\t        datas:[\r\n");



#line 24 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
 					        if (postCommand.Parameters != null && postCommand.Parameters.Any())
             {
                 foreach (var parameter in postCommand.Parameters)
                 {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                                {name:\"");



#line 29 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, parameter.Key);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\",value:\"");



#line 29 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
                      WebViewPage.WriteTo(@__razor_helper_writer, parameter.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"}  ");



#line 29 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
                                            WebViewPage.WriteTo(@__razor_helper_writer, parameter.Key == postCommand.Parameters.Last().Key ? "" : ",");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n                                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 31 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"
                 }
             }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t\t\t\t               ]\r\n\t\t\t        });\r\n\t\t\t\t}\r\n\t\t\t);\r\n\t\t});\r\n\t\t\r\n    </script>\r\n");



#line 40 "..\..\Views\ListViewCommands\PostViewCommand.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
