#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.ListViewCommands
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
    using BudgetOnline.UI.Models.ViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class RedirectViewCommand
    {
        
        #line 5 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"


        #line default
        #line hidden

public static System.Web.WebPages.HelperResult Render(ViewCommandUIModel command)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
 
    var redirectCommand = command.Command as RedirectViewCommandModel;
    if(redirectCommand == null)
	{
		throw new HttpException(404, "ViewCommand has invalid argument!");
	}
    
    var iconClass = command.IconCssClass;
    if (string.IsNullOrWhiteSpace(iconClass))
    {
        iconClass = "";
    }

    var href = "#";
    if (!string.IsNullOrWhiteSpace(redirectCommand.Path))
    {
        href = redirectCommand.Path;
    }
    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\t<a href=\"");



#line 28 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, href);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"><i class=\"glyphicon ");



#line 28 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, iconClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i>");



#line 28 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
          WebViewPage.WriteTo(@__razor_helper_writer, command.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 29 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
