#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.ListViewCommands
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
    using BudgetOnline.UI.Models.ViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public static class ViewCommandUIDefault
    {
        
        #line 3 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"


        #line default
        #line hidden

public static System.Web.WebPages.HelperResult Render(ViewCommandUIModel command)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
     
        if (command.IsVisible)
        {
            var iconForDefaultCommand = command.IconCssClass;
            if (string.IsNullOrWhiteSpace(iconForDefaultCommand))
            {
                iconForDefaultCommand = "icon-list";
            }

            
            if (command.Command.CommandType == CommandType.Post)
            {
            }
            else if (command.Command.CommandType == CommandType.Redirect)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<a class=\"btn btn-mini\" href=\"");



#line 21 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, (command.Command as RedirectViewCommandModel).Path);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"><i class=\"");



#line 21 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
                                                    WebViewPage.WriteTo(@__razor_helper_writer, iconForDefaultCommand);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"></i><span style=\"padding-left: 1em\">");



#line 21 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
                                                                                                                WebViewPage.WriteTo(@__razor_helper_writer, command.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span></a>\r\n");



#line 22 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
            }
        }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
