#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.ListViewCommands
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
    using BudgetOnline.UI.Models.ViewCommands;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
    using BudgetOnline.UI.Views.ListViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class ViewCommandUI
    {
        
        #line 4 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"


        #line default
        #line hidden

public static System.Web.WebPages.HelperResult Render(ViewCommandUIModel command, bool isRoot)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
     
        if (command.IsVisible)
        {
            if (command.IsDividerBefore)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li class=\"divider\"></li>\r\n");



#line 13 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
            }

            if (command.ChildCommands != null && command.ChildCommands.Any())
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li class=\"dropdown");



#line 17 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, !isRoot ? "-submenu" : "");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">");



#line 18 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
                        WebViewPage.WriteTo(@__razor_helper_writer, command.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 19 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
                     if (isRoot)
                    {
                    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <b class=\"caret\"></b></a>\r\n        <ul class=\"dropdown-menu\">" +
"\r\n");



#line 24 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
             foreach (var childItem in command.ChildCommands)
            {
                
#line default
#line hidden


#line 26 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, ViewCommandUI.Render(childItem, false));

#line default
#line hidden


#line 26 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
                                                         
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </ul>\r\n    </li>\r\n");



#line 30 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
            }
            else if (command.Command.CommandType == CommandType.Post)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li role=\"presentation\" class=\"t3\">");



#line 33 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, PostViewCommand.Render(command));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 34 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
            }
            else if (command.Command.CommandType == CommandType.Redirect)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li role=\"presentation\" class=\"t4\">");



#line 37 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, RedirectViewCommand.Render(command));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 38 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
            }
            else if (command.Command.CommandType == CommandType.Js)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li role=\"presentation\" class=\"t4\">");



#line 41 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, JsViewCommand.Render(command));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 42 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
            }

            if (command.IsDividerAfter)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <li class=\"divider\"></li>\r\n");



#line 47 "..\..\Views\ListViewCommands\ViewCommandUI.cshtml"
            }
        }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
