#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.ListViewCommands
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
    using BudgetOnline.UI.Models.ViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class ViewCommandUIDefault : System.Web.WebPages.HelperPage
    {

#line 8 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
public static System.Web.WebPages.HelperResult Render(ViewCommandUIModel command)
    {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 9 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
     
        if (command.IsVisible)
        {
            var iconForDefaultCommand = command.IconCssClass;
            if (string.IsNullOrWhiteSpace(iconForDefaultCommand))
            {
                iconForDefaultCommand = "glyphicon-list";
            }
            
            if (command.Command.CommandType == CommandType.Post)
            {
            }
            else if (command.Command.CommandType == CommandType.Redirect)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "<a");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default btn-xs\"");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 660), Tuple.Create("\"", 720)

#line 23 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
, Tuple.Create(Tuple.Create("", 667), Tuple.Create<System.Object, System.Int32>((command.Command as RedirectViewCommandModel).Path

#line default
#line hidden
, 667), false)
);

WriteLiteralTo(__razor_helper_writer, "><i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 724), Tuple.Create("\"", 764)
, Tuple.Create(Tuple.Create("", 732), Tuple.Create("glyphicon", 732), true)

#line 23 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
                                   , Tuple.Create(Tuple.Create(" ", 741), Tuple.Create<System.Object, System.Int32>(iconForDefaultCommand

#line default
#line hidden
, 742), false)
);

WriteLiteralTo(__razor_helper_writer, "></i><span");

WriteLiteralTo(__razor_helper_writer, " style=\"padding-left: 1em\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 23 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
                                                                                                                                                 WriteTo(__razor_helper_writer, command.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span></a>\r\n");


#line 24 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
            }
        }


#line default
#line hidden
});

#line 26 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
