#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
    using BudgetOnline.UI.PreCompiled.Models.ViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class _Views_ListViewCommands_RedirectViewCommand_cshtml : System.Web.WebPages.HelperPage
    {
        
        #line 4 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
            

        #line default
        #line hidden

#line 7 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
public static System.Web.WebPages.HelperResult Render(ViewCommandUIModel command)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 8 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
 
    var redirectCommand = command.Command as RedirectViewCommandModel;
    if(redirectCommand == null)
	{
		throw new HttpException(404, "ViewCommand has invalid argument!");
	}
    
    var iconClass = command.IconCssClass;
    if (string.IsNullOrWhiteSpace(iconClass))
    {
        iconClass = "";
    }

    var href = "#";
    if (!string.IsNullOrWhiteSpace(redirectCommand.Path))
    {
        href = redirectCommand.Path;
    }
    


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\t<a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 613), Tuple.Create("\"", 625)

#line 27 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
, Tuple.Create(Tuple.Create("", 620), Tuple.Create<System.Object, System.Int32>(href

#line default
#line hidden
, 620), false)
);

WriteLiteralTo(__razor_helper_writer, "><i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 629), Tuple.Create("\"", 657)
, Tuple.Create(Tuple.Create("", 637), Tuple.Create("glyphicon", 637), true)

#line 27 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
, Tuple.Create(Tuple.Create(" ", 646), Tuple.Create<System.Object, System.Int32>(iconClass

#line default
#line hidden
, 647), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>");


#line 27 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
                       WriteTo(__razor_helper_writer, command.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


#line 28 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"


#line default
#line hidden
});

#line 28 "..\..\Views\ListViewCommands\RedirectViewCommand.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
