#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
    using BudgetOnline.UI.PreCompiled.Models.ViewCommands;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class _Views_ListViewCommands_ViewCommandUIDefault_cshtml : System.Web.WebPages.HelperPage
    {
        
        #line 4 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
            

        #line default
        #line hidden

#line 7 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
public static System.Web.WebPages.HelperResult Render(ViewCommandUIModel model)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 8 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
 
    if (model.IsVisible)
    {
        var iconForDefaultCommand = model.IconCssClass;
        if (string.IsNullOrWhiteSpace(iconForDefaultCommand))
        {
            iconForDefaultCommand = "glyphicon-list";
        }


        if (model.Command.CommandType == CommandType.Post)
        {
        }
        else if (model.Command.CommandType == CommandType.Redirect && model.Command is RedirectViewCommandModel)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <a");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default btn-xs\"");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 636), Tuple.Create("\"", 693)

#line 23 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
, Tuple.Create(Tuple.Create("", 643), Tuple.Create<System.Object, System.Int32>(((RedirectViewCommandModel) model.Command).Path

#line default
#line hidden
, 643), false)
);

WriteLiteralTo(__razor_helper_writer, "><i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 697), Tuple.Create("\"", 737)
, Tuple.Create(Tuple.Create("", 705), Tuple.Create("glyphicon", 705), true)

#line 23 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
                                            , Tuple.Create(Tuple.Create(" ", 714), Tuple.Create<System.Object, System.Int32>(iconForDefaultCommand

#line default
#line hidden
, 715), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n                <span");

WriteLiteralTo(__razor_helper_writer, " style=\"padding-left: 1em\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 24 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
                   WriteTo(__razor_helper_writer, model.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span></a>\r\n");


#line 25 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
        }
    }


#line default
#line hidden
});

#line 27 "..\..\Views\ListViewCommands\ViewCommandUIDefault.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
