#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.Editors
{
    using System;
    using System.Collections.Generic;
    
    #line 6 "..\..\Views\Editors\CurrencyBundle.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 7 "..\..\Views\Editors\CurrencyBundle.cshtml"
    using BudgetOnline.UI.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class CurrencyBundle : System.Web.WebPages.HelperPage
    {

#line 9 "..\..\Views\Editors\CurrencyBundle.cshtml"
public static System.Web.WebPages.HelperResult Render(BudgetOnline.UI.Models.Editors.CurrencyBundle model, string propertyName, ModelState state, IDictionary<string, object> additionalValues)
    {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 10 "..\..\Views\Editors\CurrencyBundle.cshtml"
     
        var id = UIHelper.GenerateRandomCode(10);

        var placeholder = "";
        if (additionalValues.ContainsKey("placeholder"))
        {
            placeholder = additionalValues["placeholder"].ToString();
        }

        var value = model.Sum.ToString(CultureInfo.CurrentUICulture);

        var cssFormulaClass = " col-md-10 data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssFormulaClass += " input-validation-error";
        }

        var cssCurrencyListClass = " data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssCurrencyListClass += " input-validation-error";
        }

        var cssAccountListClass = " data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssAccountListClass += " input-validation-error";
        }



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1256), Tuple.Create("\"", 1264)

#line 39 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1261), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1261), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-4\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 42 "..\..\Views\Editors\CurrencyBundle.cshtml"
WriteTo(__razor_helper_writer, BudgetOnline.UI.Views.Editors.SelectList.Render(model.Account.Items, propertyName + ".Account", cssAccountListClass, false));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </div>\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-1\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            </div>\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-4\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group col-md-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 1719), Tuple.Create("\"", 1749)

#line 49 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1726), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 1726), false)
, Tuple.Create(Tuple.Create("", 1741), Tuple.Create(".Formula", 1741), true)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1750), Tuple.Create("\"", 1778)

#line 49 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1755), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 1755), false)
, Tuple.Create(Tuple.Create("", 1770), Tuple.Create("_Formula", 1770), true)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 1779), Tuple.Create("\"", 1803)

#line 49 "..\..\Views\Editors\CurrencyBundle.cshtml"
                               , Tuple.Create(Tuple.Create("", 1787), Tuple.Create<System.Object, System.Int32>(model.Formula

#line default
#line hidden
, 1787), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1804), Tuple.Create("\"", 1828)

#line 49 "..\..\Views\Editors\CurrencyBundle.cshtml"
                                                       , Tuple.Create(Tuple.Create("", 1812), Tuple.Create<System.Object, System.Int32>(cssFormulaClass

#line default
#line hidden
, 1812), false)
);

WriteLiteralTo(__razor_helper_writer, " autocomplete = \"off\" placeholder=\"");


#line 49 "..\..\Views\Editors\CurrencyBundle.cshtml"
                                                                                                                                                             WriteTo(__razor_helper_writer, placeholder);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"/>\r\n                        <span");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-comment\"");

WriteLiteralTo(__razor_helper_writer, "></i></span>\r\n                    </div>\r\n                </div>\r\n               " +
" <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group col-md-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 2175), Tuple.Create("\"", 2201)

#line 55 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 2182), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 2182), false)
, Tuple.Create(Tuple.Create("", 2197), Tuple.Create(".Sum", 2197), true)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 2202), Tuple.Create("\"", 2226)

#line 55 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 2207), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 2207), false)
, Tuple.Create(Tuple.Create("", 2222), Tuple.Create("_Sum", 2222), true)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 2227), Tuple.Create("\"", 2241)

#line 55 "..\..\Views\Editors\CurrencyBundle.cshtml"
                      , Tuple.Create(Tuple.Create("", 2235), Tuple.Create<System.Object, System.Int32>(value

#line default
#line hidden
, 2235), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"form-control input-sm calculator-result\"");

WriteLiteralTo(__razor_helper_writer, " readonly = \"readonly\" autocomplete = \"off\" title = \"Результат из поля Сумма\"/>\r\n" +
"                    </div>\r\n                </div>\r\n            </div>\r\n        " +
"    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-3\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 60 "..\..\Views\Editors\CurrencyBundle.cshtml"
WriteTo(__razor_helper_writer, BudgetOnline.UI.Views.Editors.SelectList.Render(model.Currency.Items, propertyName + ".Currency", cssCurrencyListClass, false));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ")\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <script");

WriteLiteralTo(__razor_helper_writer, " type=\"text/javascript\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        $(document).ready(function () {\r\n            turnOn_calculator(\'");


#line 66 "..\..\Views\Editors\CurrencyBundle.cshtml"
  WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n        });\r\n    </script>\r\n");


#line 69 "..\..\Views\Editors\CurrencyBundle.cshtml"


#line default
#line hidden
});

#line 69 "..\..\Views\Editors\CurrencyBundle.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
