#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Editors\CurrencyBundle.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Views\Editors\CurrencyBundle.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Editors/CurrencyBundle.cshtml")]
    public partial class _Views_Editors_CurrencyBundle_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {

#line 5 "..\..\Views\Editors\CurrencyBundle.cshtml"
public System.Web.WebPages.HelperResult Render(BudgetOnline.UI.Models.Editors.CurrencyBundle model, string propertyName, ModelState state, IDictionary<string, object> additionalValues)
    {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 6 "..\..\Views\Editors\CurrencyBundle.cshtml"
     
        var id = Html.GetUniqId(10);

        var placeholder = "";
        if (additionalValues.ContainsKey("placeholder"))
        {
            placeholder = additionalValues["placeholder"].ToString();
        }

        var value = model.Sum.ToString(CultureInfo.CurrentUICulture);

        var cssFormulaClass = " col-md-10 data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssFormulaClass += " input-validation-error";
        }

        var cssCurrencyListClass = " data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssCurrencyListClass += " input-validation-error";
        }

        var cssAccountListClass = " data-type-calculator form-control";
        if (state != null && state.Errors.Count > 0)
        {
            cssAccountListClass += " input-validation-error";
        }



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1181), Tuple.Create("\"", 1189)

#line 35 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1186), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 1186), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-4\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 38 "..\..\Views\Editors\CurrencyBundle.cshtml"
WriteTo(__razor_helper_writer, new _Views_Editors_SelectList_cshtml().Render(model.Account.Items, propertyName + ".Account", cssAccountListClass, false));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </div>\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-1\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            </div>\r\n            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-4\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group col-md-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 1644), Tuple.Create("\"", 1674)

#line 45 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1651), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 1651), false)
, Tuple.Create(Tuple.Create("", 1666), Tuple.Create(".Formula", 1666), true)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 1675), Tuple.Create("\"", 1703)

#line 45 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 1680), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 1680), false)
, Tuple.Create(Tuple.Create("", 1695), Tuple.Create("_Formula", 1695), true)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 1704), Tuple.Create("\"", 1728)

#line 45 "..\..\Views\Editors\CurrencyBundle.cshtml"
                               , Tuple.Create(Tuple.Create("", 1712), Tuple.Create<System.Object, System.Int32>(model.Formula

#line default
#line hidden
, 1712), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1729), Tuple.Create("\"", 1753)

#line 45 "..\..\Views\Editors\CurrencyBundle.cshtml"
                                                       , Tuple.Create(Tuple.Create("", 1737), Tuple.Create<System.Object, System.Int32>(cssFormulaClass

#line default
#line hidden
, 1737), false)
);

WriteLiteralTo(__razor_helper_writer, " autocomplete = \"off\" placeholder=\"");


#line 45 "..\..\Views\Editors\CurrencyBundle.cshtml"
                                                                                                                                                             WriteTo(__razor_helper_writer, placeholder);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"/>\r\n                        <span");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group-addon\"");

WriteLiteralTo(__razor_helper_writer, "><i");

WriteLiteralTo(__razor_helper_writer, " class=\"glyphicon glyphicon-comment\"");

WriteLiteralTo(__razor_helper_writer, "></i></span>\r\n                    </div>\r\n                </div>\r\n               " +
" <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"input-group col-md-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <input");

WriteLiteralTo(__razor_helper_writer, " type=\"text\"");

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 2100), Tuple.Create("\"", 2126)

#line 51 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 2107), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 2107), false)
, Tuple.Create(Tuple.Create("", 2122), Tuple.Create(".Sum", 2122), true)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 2127), Tuple.Create("\"", 2151)

#line 51 "..\..\Views\Editors\CurrencyBundle.cshtml"
, Tuple.Create(Tuple.Create("", 2132), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 2132), false)
, Tuple.Create(Tuple.Create("", 2147), Tuple.Create("_Sum", 2147), true)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 2152), Tuple.Create("\"", 2166)

#line 51 "..\..\Views\Editors\CurrencyBundle.cshtml"
                      , Tuple.Create(Tuple.Create("", 2160), Tuple.Create<System.Object, System.Int32>(value

#line default
#line hidden
, 2160), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"form-control input-sm calculator-result\"");

WriteLiteralTo(__razor_helper_writer, " readonly = \"readonly\" autocomplete = \"off\" title = \"Результат из поля Сумма\"/>\r\n" +
"                    </div>\r\n                </div>\r\n            </div>\r\n        " +
"    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-3\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 56 "..\..\Views\Editors\CurrencyBundle.cshtml"
WriteTo(__razor_helper_writer, new _Views_Editors_SelectList_cshtml().Render(model.Currency.Items, propertyName + ".Currency", cssCurrencyListClass, false));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <script");

WriteLiteralTo(__razor_helper_writer, " type=\"text/javascript\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        $(document).ready(function () {\r\n            turnOn_calculator(\'");


#line 62 "..\..\Views\Editors\CurrencyBundle.cshtml"
  WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n        });\r\n    </script>\r\n");


#line 65 "..\..\Views\Editors\CurrencyBundle.cshtml"


#line default
#line hidden
});

#line 65 "..\..\Views\Editors\CurrencyBundle.cshtml"
}
#line default
#line hidden

        public _Views_Editors_CurrencyBundle_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
