#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.Editors
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
    using BudgetOnline.UI.Models.SelectItems;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class MultiColumnSelectList : System.Web.WebPages.HelperPage
    {

#line 8 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
public static System.Web.WebPages.HelperResult Render(SelectItemsModel model, string propertyName, string cssClass, bool multiSelect, int columns)
    {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 9 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
     
    var rows = Convert.ToInt32(Math.Ceiling(Convert.ToDecimal(model.Items.Count()) / columns));
    for (int r = 0; r < rows; r++)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row visible-sm visible-xs\"");

WriteLiteralTo(__razor_helper_writer, " style=\"height: 10px\"");

WriteLiteralTo(__razor_helper_writer, "></div>\r\n");

WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 15 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
        

#line default
#line hidden

#line 15 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
          
        for (int c = 0; c < columns; c++)
        {
            var index = r * columns + c;
            if (index < model.Items.Count())
            {
                var item = model.Items.ElementAt(index);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <div");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 711), Tuple.Create("\"", 791)
, Tuple.Create(Tuple.Create("", 719), Tuple.Create("col-sm-6", 719), true)
, Tuple.Create(Tuple.Create(" ", 727), Tuple.Create("col-xs-8", 728), true)
, Tuple.Create(Tuple.Create(" ", 736), Tuple.Create("col-md-", 737), true)

#line 22 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
, Tuple.Create(Tuple.Create("", 744), Tuple.Create<System.Object, System.Int32>(Convert.ToInt32(Math.Ceiling(12m / columns))

#line default
#line hidden
, 744), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n                <label");

WriteLiteralTo(__razor_helper_writer, " class=\"checkbox-inline\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <input");

WriteLiteralTo(__razor_helper_writer, " type=\"checkbox\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 886), Tuple.Create("\"", 902)

#line 24 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
, Tuple.Create(Tuple.Create("", 891), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 891), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 903), Tuple.Create("\"", 940)

#line 24 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
, Tuple.Create(Tuple.Create("", 910), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 910), false)
, Tuple.Create(Tuple.Create("", 925), Tuple.Create("[", 925), true)

#line 24 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
    , Tuple.Create(Tuple.Create("", 926), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 926), false)
, Tuple.Create(Tuple.Create("", 939), Tuple.Create("]", 939), true)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 941), Tuple.Create("\"", 959)

#line 24 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
                          , Tuple.Create(Tuple.Create("", 949), Tuple.Create<System.Object, System.Int32>(item.Text

#line default
#line hidden
, 949), false)
);

WriteLiteralTo(__razor_helper_writer, " ");


#line 24 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
                                                                                        WriteTo(__razor_helper_writer, new HtmlString(item.Selected ? "checked='checked'" : string.Empty));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "/>\r\n");

WriteLiteralTo(__razor_helper_writer, "                    ");


#line 25 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n                </label>\r\n            </div>\r\n");


#line 28 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
            }
        }
        

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n    </div>\r\n");


#line 32 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
    }


#line default
#line hidden
});

#line 33 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
