#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.Editors
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
    using BudgetOnline.UI.Models.SelectItems;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Editors/MultiColumnSelectList.cshtml")]
    public partial class MultiColumnSelectList : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 2 "..\..\Views\Editors\MultiColumnSelectList.cshtml"

    int GetRowsCount(int itemsCount, int columns)
    {
        return Convert.ToInt32(Math.Ceiling(Convert.ToDecimal(itemsCount) / columns));
    }

        #line default
        #line hidden

public System.Web.WebPages.HelperResult Render(SelectItemsModel model, string propertyName, string cssClass, bool multiSelect, int columns)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 9 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
     
    int rows = GetRowsCount(model.Items.Count(), columns);
    for (int r = 0; r < rows; r++)
    {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"row-fluid\">\r\n");



#line 14 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
          
        for (int c = 0; c < columns; c++)
        {
            var index = r * columns + c;
            if (index < model.Items.Count())
            {
                var item = model.Items.ElementAt(index);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <div class=\"span");



#line 21 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
WriteTo(@__razor_helper_writer, Convert.ToInt32(Math.Ceiling(12m / columns)));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n                <label class=\"checkbox inline\">\r\n                    <input t" +
"ype=\"checkbox\" id=\"");



#line 23 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
                WriteTo(@__razor_helper_writer, item.Value);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" name=\"");



#line 23 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
                                    WriteTo(@__razor_helper_writer, propertyName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "[");



#line 23 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
                                                    WriteTo(@__razor_helper_writer, item.Value);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "]\" value=\"");



#line 23 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
                                                                          WriteTo(@__razor_helper_writer, item.Text);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 23 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
                                                                                       WriteTo(@__razor_helper_writer, new HtmlString(item.Selected ? "checked='checked'" : string.Empty));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "/>\r\n                    ");



#line 24 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
WriteTo(@__razor_helper_writer, item.Text);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n                </label>\r\n            </div>\r\n");



#line 27 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
            }
        }
        

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    </div>\r\n");



#line 31 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
    }
    
    
    
#line default
#line hidden



#line 39 "..\..\Views\Editors\MultiColumnSelectList.cshtml"
               

#line default
#line hidden

});

}


        public MultiColumnSelectList()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");




        }
    }
}
#pragma warning restore 1591
