#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.Editors
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\Editors\SelectList.cshtml"
    using BudgetOnline.UI.Models.SelectItems;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class SelectList : System.Web.WebPages.HelperPage
    {

#line 8 "..\..\Views\Editors\SelectList.cshtml"
public static System.Web.WebPages.HelperResult Render(SelectItemsModel model, string propertyName, string cssClass, bool multiSelect)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 9 "..\..\Views\Editors\SelectList.cshtml"
 
    var id = (propertyName ?? string.Empty).Replace(".", "_");
    if (model == null)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <select");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 322), Tuple.Create("\"", 339)

#line 13 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 330), Tuple.Create<System.Object, System.Int32>(cssClass

#line default
#line hidden
, 330), false)
);

WriteLiteralTo(__razor_helper_writer, "></select>\r\n");


#line 14 "..\..\Views\Editors\SelectList.cshtml"
    }
    else if (multiSelect)
    {
        foreach (var item in model.Items)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <div");

WriteLiteralTo(__razor_helper_writer, " class=\"\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <label");

WriteLiteralTo(__razor_helper_writer, " class=\"checkbox form-inline\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                    <input");

WriteLiteralTo(__razor_helper_writer, " type=\"checkbox\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 571), Tuple.Create("\"", 587)

#line 21 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 576), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 576), false)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 588), Tuple.Create("\"", 607)

#line 21 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 596), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 596), false)
);

WriteLiteralTo(__razor_helper_writer, " ");


#line 21 "..\..\Views\Editors\SelectList.cshtml"
                                                   WriteTo(__razor_helper_writer, new HtmlString(item.Selected ? "checked='checked'" : string.Empty));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " />\r\n");

WriteLiteralTo(__razor_helper_writer, "                    ");


#line 22 "..\..\Views\Editors\SelectList.cshtml"
WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n                </label>\r\n            </div>\r\n");


#line 25 "..\..\Views\Editors\SelectList.cshtml"
        }
    }
    else
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <select");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 811), Tuple.Create("\"", 841)
, Tuple.Create(Tuple.Create("", 819), Tuple.Create("form-control", 819), true)

#line 29 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create(" ", 831), Tuple.Create<System.Object, System.Int32>(cssClass

#line default
#line hidden
, 832), false)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 842), Tuple.Create("\"", 850)

#line 29 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 847), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 847), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 851), Tuple.Create("\"", 871)

#line 29 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 858), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 858), false)
);

WriteLiteralTo(__razor_helper_writer, " ");


#line 29 "..\..\Views\Editors\SelectList.cshtml"
                                                WriteTo(__razor_helper_writer, new HtmlString(multiSelect ? "multiple='multiple'" : string.Empty));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 30 "..\..\Views\Editors\SelectList.cshtml"
            

#line default
#line hidden

#line 30 "..\..\Views\Editors\SelectList.cshtml"
             foreach (var item in model.Items)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <option");

WriteLiteralTo(__razor_helper_writer, " data-icon=\"");


#line 32 "..\..\Views\Editors\SelectList.cshtml"
     WriteTo(__razor_helper_writer, item.Icon);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 1054), Tuple.Create("\"", 1073)

#line 32 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 1062), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 1062), false)
);

WriteLiteralTo(__razor_helper_writer, " ");


#line 32 "..\..\Views\Editors\SelectList.cshtml"
                                      WriteTo(__razor_helper_writer, new HtmlString(item.Selected ? "selected='selected'" : string.Empty));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">");


#line 32 "..\..\Views\Editors\SelectList.cshtml"
                                                                                                             WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</option>\r\n");


#line 33 "..\..\Views\Editors\SelectList.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </select>\r\n");


#line 35 "..\..\Views\Editors\SelectList.cshtml"
    }


#line default
#line hidden
});

#line 36 "..\..\Views\Editors\SelectList.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
