#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.Editors
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Editors\SelectList.cshtml"
    using BudgetOnline.UI.Models.SelectItems;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Editors/SelectList.cshtml")]
    public partial class SelectList : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 2 "..\..\Views\Editors\SelectList.cshtml"



        #line default
        #line hidden

public System.Web.WebPages.HelperResult Render(SelectItemsModel model, string propertyName, string cssClass, bool multiSelect)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Views\Editors\SelectList.cshtml"
     
    var id = (propertyName ?? string.Empty).Replace(".", "_");
        if (model == null)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <select class=\"");



#line 10 "..\..\Views\Editors\SelectList.cshtml"
WriteTo(@__razor_helper_writer, cssClass);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n    </select>\r\n");



#line 12 "..\..\Views\Editors\SelectList.cshtml"
        }
        else if (multiSelect)
        {
            
    
    foreach (var item in model.Items)
    {
        //<option data-icon="@item.Icon" value="@item.Value" @(new HtmlString(item.Selected ? "selected='selected'" : string.Empty))>@item.Text</option>

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"\">\r\n        <label class=\"checkbox inline\">\r\n            <input t" +
"ype=\"checkbox\" id=\"");



#line 22 "..\..\Views\Editors\SelectList.cshtml"
        WriteTo(@__razor_helper_writer, item.Value);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 22 "..\..\Views\Editors\SelectList.cshtml"
                            WriteTo(@__razor_helper_writer, item.Value);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 22 "..\..\Views\Editors\SelectList.cshtml"
                                          WriteTo(@__razor_helper_writer, new HtmlString(item.Selected ? "checked='checked'" : string.Empty));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "/>\r\n            ");



#line 23 "..\..\Views\Editors\SelectList.cshtml"
WriteTo(@__razor_helper_writer, item.Text);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n        </label>\r\n    </div>\r\n");



#line 26 "..\..\Views\Editors\SelectList.cshtml"
    }
    
            

#line default
#line hidden



#line 29 "..\..\Views\Editors\SelectList.cshtml"
                                                            
        }
        else
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <select class=\"");



#line 33 "..\..\Views\Editors\SelectList.cshtml"
WriteTo(@__razor_helper_writer, cssClass);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" id=\"");



#line 33 "..\..\Views\Editors\SelectList.cshtml"
   WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" name=\"");



#line 33 "..\..\Views\Editors\SelectList.cshtml"
              WriteTo(@__razor_helper_writer, propertyName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 33 "..\..\Views\Editors\SelectList.cshtml"
                              WriteTo(@__razor_helper_writer, new HtmlString(multiSelect ? "multiple='multiple'" : string.Empty));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 34 "..\..\Views\Editors\SelectList.cshtml"
         foreach (var item in model.Items)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <option data-icon=\"");



#line 36 "..\..\Views\Editors\SelectList.cshtml"
WriteTo(@__razor_helper_writer, item.Icon);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 36 "..\..\Views\Editors\SelectList.cshtml"
                   WriteTo(@__razor_helper_writer, item.Value);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 36 "..\..\Views\Editors\SelectList.cshtml"
                                 WriteTo(@__razor_helper_writer, new HtmlString(item.Selected ? "selected='selected'" : string.Empty));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ">");



#line 36 "..\..\Views\Editors\SelectList.cshtml"
                                                                                                        WriteTo(@__razor_helper_writer, item.Text);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</option>\r\n");



#line 37 "..\..\Views\Editors\SelectList.cshtml"
        }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    </select>\r\n");



#line 39 "..\..\Views\Editors\SelectList.cshtml"
            

#line default
#line hidden



#line 40 "..\..\Views\Editors\SelectList.cshtml"
                                                            
        }

#line default
#line hidden

});

}


        public SelectList()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");




        }
    }
}
#pragma warning restore 1591
