#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetOnline.UI.Views.Editors
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\Editors\SelectList.cshtml"
    using BudgetOnline.UI.Models.SelectItems;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class SelectList : System.Web.WebPages.HelperPage
    {

#line 8 "..\..\Views\Editors\SelectList.cshtml"
public static System.Web.WebPages.HelperResult Render(SelectItemsModel model, string propertyName, string cssClass, bool multiSelect)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 9 "..\..\Views\Editors\SelectList.cshtml"
 
    var id = (propertyName ?? string.Empty).Replace(".", "_");
    if (model == null)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <select");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 322), Tuple.Create("\"", 339)

#line 13 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 330), Tuple.Create<System.Object, System.Int32>(cssClass

#line default
#line hidden
, 330), false)
);

WriteLiteralTo(__razor_helper_writer, "></select>\r\n");


#line 14 "..\..\Views\Editors\SelectList.cshtml"
    }
    else if (multiSelect)
    {
        foreach (var item in model.Items)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <label");

WriteLiteralTo(__razor_helper_writer, " class=\"checkbox form-inline\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n                <input");

WriteLiteralTo(__razor_helper_writer, " type=\"checkbox\"");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 535), Tuple.Create("\"", 551)

#line 20 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 540), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 540), false)
);

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 552), Tuple.Create("\"", 571)

#line 20 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 560), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 560), false)
);

WriteLiteralTo(__razor_helper_writer, " ");


#line 20 "..\..\Views\Editors\SelectList.cshtml"
                                               WriteTo(__razor_helper_writer, new HtmlString(item.Selected ? "checked='checked'" : string.Empty));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " />\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 21 "..\..\Views\Editors\SelectList.cshtml"
WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </label>\r\n");


#line 23 "..\..\Views\Editors\SelectList.cshtml"
        }
    }
    else
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <select");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 747), Tuple.Create("\"", 777)
, Tuple.Create(Tuple.Create("", 755), Tuple.Create("form-control", 755), true)

#line 27 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create(" ", 767), Tuple.Create<System.Object, System.Int32>(cssClass

#line default
#line hidden
, 768), false)
);

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 778), Tuple.Create("\"", 786)

#line 27 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 783), Tuple.Create<System.Object, System.Int32>(id

#line default
#line hidden
, 783), false)
);

WriteAttributeTo(__razor_helper_writer, "name", Tuple.Create(" name=\"", 787), Tuple.Create("\"", 807)

#line 27 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 794), Tuple.Create<System.Object, System.Int32>(propertyName

#line default
#line hidden
, 794), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 28 "..\..\Views\Editors\SelectList.cshtml"
            

#line default
#line hidden

#line 28 "..\..\Views\Editors\SelectList.cshtml"
             foreach (var item in model.Items)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <option");

WriteLiteralTo(__razor_helper_writer, " data-icon=\"");


#line 30 "..\..\Views\Editors\SelectList.cshtml"
     WriteTo(__razor_helper_writer, item.Icon);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteAttributeTo(__razor_helper_writer, "value", Tuple.Create(" value=\"", 920), Tuple.Create("\"", 939)

#line 30 "..\..\Views\Editors\SelectList.cshtml"
, Tuple.Create(Tuple.Create("", 928), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 928), false)
);

WriteLiteralTo(__razor_helper_writer, " ");


#line 30 "..\..\Views\Editors\SelectList.cshtml"
                                      WriteTo(__razor_helper_writer, new HtmlString(item.Selected ? "selected='selected'" : string.Empty));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">");


#line 30 "..\..\Views\Editors\SelectList.cshtml"
                                                                                                             WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</option>\r\n");


#line 31 "..\..\Views\Editors\SelectList.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </select>\r\n");


#line 33 "..\..\Views\Editors\SelectList.cshtml"
    }


#line default
#line hidden
});

#line 34 "..\..\Views\Editors\SelectList.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
