#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\CurrencyRates\List.cshtml"
    using BudgetOnline.UI.Controls;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Admin\Views\CurrencyRates\List.cshtml"
    using BudgetOnline.Web.Areas.Admin.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/CurrencyRates/List.cshtml")]
    public partial class _Areas_Admin_Views_CurrencyRates_List_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<CurrencyRateListViewModel>>
    {
        public _Areas_Admin_Views_CurrencyRates_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\CurrencyRates\List.cshtml"
  
    ViewBag.Title = "Курсы валют";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"btn-toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"btn\"");

WriteAttribute("href", Tuple.Create(" href=\"", 313), Tuple.Create("\"", 341)
            
            #line 10 "..\..\Areas\Admin\Views\CurrencyRates\List.cshtml"
, Tuple.Create(Tuple.Create("", 320), Tuple.Create<System.Object, System.Int32>(Url.Action("create")
            
            #line default
            #line hidden
, 320), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon-plus\"");

WriteLiteral("></i>Новая запись</a>\r\n    </div>\r\n</div>\r\n");

            
            #line 13 "..\..\Areas\Admin\Views\CurrencyRates\List.cshtml"
Write(Html.BudgetOnlineWeb()
    .Table<CurrencyRateListViewModel>()
    .Css("table table-striped")
    .OutputType(TableBuilderOutputTypes.Table)
    .Rows(Model)
    .Columns(columns =>
                {
                    columns.Bound(m => m.Date).Span(3).Formatter<DateTime>(o => o.ToLocalTime().ToShortDateString());
                    columns.Icon().IconCss(m => m.IsDisabled ? "glyphicon-lock" : (m.IsDisabled ? "glyphicon-lock" : "")).Span(1);
                    columns.Bound(m => m.BaseCurrencyName).Span(3);
                    columns.Bound(m => m.TargetCurrencyName).Span(3);
                    columns.Bound(m => m.Rate).Span(3);
                    columns.Commands().Cell(m => m.Commands).Span(2);
                })
    .Build());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
