#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Users/Disable.cshtml")]
    public partial class _Areas_Admin_Views_Users_Disable_cshtml : System.Web.Mvc.WebViewPage<BudgetOnline.Web.Areas.Admin.Models.EnableDisableUserViewModel>
    {
        public _Areas_Admin_Views_Users_Disable_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
  
	ViewBag.Title = "Блокировать пользователя";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>\r\n\tБлокировать пользователя</h3>\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
 if (Model.IsDisabled)
{

            
            #line default
            #line hidden
WriteLiteral("\t<p>\r\n\t\tПользователь уже заблокирован</p>\r\n");

WriteLiteral("\t<p>\r\n");

WriteLiteral("\t\t");

            
            #line 13 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
Write(Html.BudgetOnlineWeb().ButtonNormal().Caption("Отмена").RedirectTo(Url.Action("list")).Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</p>\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("\t<p>\r\n\t\tВы действительно хотите заблокировать пользователя</p>\r\n");

WriteLiteral("\t<br />\r\n");

WriteLiteral("\t<p>");

            
            #line 21 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 21 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
            Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n");

WriteLiteral("\t<br />\r\n");

WriteLiteral("\t<p>\r\n");

WriteLiteral("\t\t");

            
            #line 24 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
Write(Html.BudgetOnlineWeb().Form().ActionUrl(Url.Action("disable"))
       	.Content(item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 26 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
				  	
            
            #line default
            #line hidden
            
            #line 26 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
        Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 27 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
				  	
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
        Html.BudgetOnlineWeb().PrimaryButton().Caption("Продолжить").Build());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 28 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
				  	
            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
        Html.BudgetOnlineWeb().ButtonNormal().Caption("Отмена").RedirectTo(Url.Action("list")).Build());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n\t\t\t\t  ");

            
            #line 29 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
           }))
			.Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</p>\r\n");

            
            #line 32 "..\..\Areas\Admin\Views\Users\Disable.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
