#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
    using BudgetOnline.Web.UI.Controls;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Users/Enable.cshtml")]
    public partial class _Areas_Admin_Views_Users_Enable_cshtml : System.Web.Mvc.WebViewPage<BudgetOnline.Web.Areas.Admin.Models.EnableDisableUserViewModel>
    {
        public _Areas_Admin_Views_Users_Enable_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
  
	ViewBag.Title = "Разблокировать пользователя";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>\r\n\tРазблокировать пользователя</h3>\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
 if (!Model.IsDisabled)
{

            
            #line default
            #line hidden
WriteLiteral("\t<p>\r\n\t\tПользователь уже разблокирован</p>\r\n");

WriteLiteral("\t<p>\r\n");

WriteLiteral("\t\t");

            
            #line 14 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
Write(Html.BudgetOnlineWeb().ButtonNormal().Caption("Отмена").RedirectTo(Url.Action("list")).Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</p>\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("\t<p>\r\n\t\tВы действительно хотите разблокировать пользователя</p>\r\n");

WriteLiteral("\t<br />\r\n");

WriteLiteral("\t<p>");

            
            #line 22 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 22 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
            Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n");

WriteLiteral("\t<br />\r\n");

WriteLiteral("\t<p>\r\n");

WriteLiteral("\t\t");

            
            #line 25 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
Write(Html.BudgetOnlineWeb()
			.Form(BudgetOnlineWebControls.FormTypes.Horizontal)
			.ActionUrl(Url.Action("enable"))
			.Content(item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 29 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
			
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
    Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 30 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
			
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
    Html.BudgetOnlineWeb().PrimaryButton().Caption("Продолжить").Build());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n");

WriteTo(__razor_template_writer, 
            
            #line 31 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
			
            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
    Html.BudgetOnlineWeb().ButtonNormal().Caption("Отмена").RedirectTo(Url.Action("list")).Build());

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n\t\t\t");

            
            #line 32 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
        }))
			.Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</p>\r\n");

            
            #line 35 "..\..\Areas\Admin\Views\Users\Enable.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
