#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\Users\List.cshtml"
    using BudgetOnline.Web.Areas.Admin.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Admin\Views\Users\List.cshtml"
    using BudgetOnline.Web.UI.Controls;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Users/List.cshtml")]
    public partial class _Areas_Admin_Views_Users_List_cshtml : System.Web.Mvc.WebViewPage<UserListViewModel>
    {
        public _Areas_Admin_Views_Users_List_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Users\List.cshtml"
  
    ViewBag.Title = "List";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayoutPage.cshtml";

    var searchBy = string.Empty;
    if (!string.IsNullOrWhiteSpace(Model.Search.Text))
    {
        searchBy = Model.Search.Text;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Areas\Admin\Views\Users\List.cshtml"
   Write(Html.BudgetOnlineWeb().PrimaryButton().Caption("Новая запись").RedirectTo(Url.Action("create")).Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Areas\Admin\Views\Users\List.cshtml"
    Write(Html.BudgetOnlineWeb()
        .Form(BudgetOnlineWebControls.FormTypes.Inline)
        .Css("pull-right")
        .Id("searchForm")
        .SubmitClientAction(Url.Action("list"))
        .Content(item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden
WriteLiteralTo(__razor_template_writer, "\r\n        <input");

WriteLiteralTo(__razor_template_writer, " name=\"searchBy\"");

WriteLiteralTo(__razor_template_writer, " type=\"text\"");

WriteLiteralTo(__razor_template_writer, " placeholder=\"Имя или Email\"");

WriteAttributeTo(__razor_template_writer, "value", Tuple.Create(" value=\"", 848), Tuple.Create("\"", 865)
            
            #line 25 "..\..\Areas\Admin\Views\Users\List.cshtml"
, Tuple.Create(Tuple.Create("", 856), Tuple.Create<System.Object, System.Int32>(searchBy
            
            #line default
            #line hidden
, 856), false)
);

WriteLiteralTo(__razor_template_writer, " class=\"\"");

WriteLiteralTo(__razor_template_writer, " />\r\n        <button");

WriteLiteralTo(__razor_template_writer, " class=\"btn\"");

WriteLiteralTo(__razor_template_writer, " type=\"submit\"");

WriteLiteralTo(__razor_template_writer, " name=\"search\"");

WriteLiteralTo(__razor_template_writer, ">\r\n            Поиск</button>\r\n        ");

WriteLiteralTo(__razor_template_writer, "\r\n        ");

            
            #line 30 "..\..\Areas\Admin\Views\Users\List.cshtml"
             })).Build());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\Users\List.cshtml"
Write(Html.BudgetOnlineWeb()
    .Table<UserListItemsViewModel>()
    .Css("table table-striped")
    .Rows(Model.Items)
    .Columns(columns =>
                {
                    columns.Icon().IconCss(m => m.IsBocked ?
                        "glyphicon-lock" :
                        (m.IsReadOnly ? "glyphicon-eye-open" : (m.IsAdmin ? "glyphicon-wrench" : ""))
                    ).Span(1);
                    columns.Bound(m => m.Name).Span(4);
                    columns.Bound(m => m.Email).Span(2);
                    columns.Bound(m => m.WhenLastConnected).Span(4);
                    columns.Commands().Cell(m => m.Commands).Span(2);
                })
    .Build()
    );

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(document).ready(function () {\r\n        $(\'#searchForm button[name=\"clear" +
"\"]\').click(function () {\r\n            clearForm($(\'#searchForm\').get());\r\n      " +
"  });\r\n    });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
